### ISSUE TITLE
Get rid of FlxTypedGroup's setAll() and callAll()

### ISSUE THREAD

**Issue by Gama11** [HaxeFlixel/flixel#1086]
They are extremely slow and encourage bad programming practices (string-based member access / reflection).

forEach()-functions should be used instead, but they would need an additional "Recursive" param to provide the same functionality, which requires casting. That param should be false by default.

**Comment by sano98** [comment]
I used setAll() in my code to set some values of all the members of the group, like here:
this.constructionBoxGroup.setAll("allowCollisions", false, true);

As far as I understand it, forEach() only lets you use a function of each member, but not maipulate a field directly. Since "allowCollisions", in this example, doesn't have a getter/setter, I can't use forEach()  that way.

Either all relevant fields need getter/setter with this implementation, or I have to write a "setter"-like method in the class where I want to manipulate, like:

public function set_allowCollisions(target:FlxObject, value:bool):Void
{
    target.allowCollisions = bool;
}

Is this the way it is intended?

**Comment by Gama11** [comment]
@sano98 Yes, `forEach()` executes a function on each member, although typically you would use an anonymous function. Fields don't need a setter / getter, since you manipulate the member in that function.

Also, `allowCollisions` is of type `Int`, you shouldn't be assigning boolean values to it. You can do one of the following to accomplish the same:

- `allowCollisions = FlxObject.NONE`
- `solid = false`

Here's an example of `forEach()` with an anonymous function:

```haxe
constructionBoxGroup.forEach(function (member) {
   member.solid = false;
}, true);
```

Granted, this is slightly longer than the previous version with `setAll()`, but also type-safe and *much* faster.

**Comment by sano98** [comment]
Okay, cool. Thank you. As the group could contains FlxObjects *and* other groups, but only FlxObject has the solid or allowCollisions-variable, (FlxBasic does not), I had to make sure that the `forEach()` is only executed on the FlxObjects:
```haxe
this.constructionBoxGroup.forEachOfType(FlxObject, function (member) 
{ member.allowCollisions = FlxObject.NONE; }, true);
```
