### ISSUE TITLE
Weird player movement.

### ISSUE THREAD

**Issue by nazywam** [HaxeFlixel/flixel#1260]
I've noticed a weird player movement. Basically, the player moves few pixels right and then goes back.
It only happens when the camera is scrolling with the player.
Explanatory gifs:
http://i.imgur.com/6VDzlbS.gif
http://i.imgur.com/bVcGl7X.gif

I set the camera by:
```
FlxG.worldBounds.set(0, 0, map.width, map.height);
FlxG.camera.setScrollBoundsRect(0, 0, map.width, map.height);
FlxG.camera.follow(player, FlxCameraFollowStyle.PLATFORMER);
```
I do not use followLerp.
Thanks for help!

**Comment by Gama11** [comment]
@JoeCreates Any new thoughts? Bug / no bug?

**Comment by JoeCreates** [comment]
I'm not sure, but I think it might be a bug related to which values (the players actual floating position/the players floored position) the camera uses to determine how much it should move. I would have expected with pixelperfectposition and pixelperfectrender both false on everything, this wouldn't appear. If it does then there is a bug.

You would still expect the kind of jitter whereby some frames the map moves 2 pixels, and some frames it moves 1, but this is the only way it can work if you want to have everything snap to pixels but still move in real steps rather than integers. The jittering in the gifs is not this, though.

**Comment by Gama11** [comment]
As pointed out earlier by @sruloart `pixelPerfectPosition = false` _does_ fix the issue. So, no bug?

**Comment by Gama11** [comment]
I take that as a yes.
