### ISSUE TITLE
FlxText not showing up on android.

### ISSUE THREAD

**Issue by solewalker** [HaxeFlixel/flixel#1399]
FlxText is not showing up on android target. It was working a while back.

**Comment by Tiago-Ling** [comment]
Hey, i did have this issue sometime ago, but at least on dev this is not happening anymore for me. Even when it was happening, it seemed more of a default font embedding problem than a text rendering one.

It's been a while since i saw this problem happening - can somebody confirm it is still happening in flixel dev?

**Comment by Gama11** [comment]
@Tiago-Ling I'm still not seeing any text on the FlxButtons in Mode.
