### ISSUE TITLE
Jumpy animated sprites from trimmed Texture Packer atlas

### ISSUE THREAD

**Issue by jotson** [HaxeFlixel/flixel#1418]
When I load frames for an animation from a Texture Packer atlas with trim enabled (transparent pixels are removed from atlas) the animation can wiggle from frame to frame if the trimmed sizes of each frame are different. Is this expected behavior? If not, I can provide an example project that demonstrates the problem.

**Comment by MSGhero** [comment]
This is actually due to the source images not being properly sized. TP defaults to placing the registration point in the center of the image I think. If the center of one image doesn't line up with the center of the next image, the second image will look like it wiggles when in reality it's lining up centers.

The solution to this is to make all source images of an animation the same size. If they're all the same size, their centers are all in the same location and there won't be any shifting. The character needs to be animated within this box relative to this box, so it has to be big enough to hold all the frames of animation.

**Comment by jotson** [comment]
That's not what is happening in this case. With Flash target the animation plays correctly. With CPP target (neko) the animation jumps around. Here's an example project that shows the problem: https://dl.dropboxusercontent.com/u/7063628/texturepacker-trim-example.zip

I've confirmed that the JSON data is correct and I've included the original assets so you can flip through them and see that they are all sized and aligned correctly.

My haxelib versions:

flixel-addons: [1.1.0] 1.0.3
flixel-demos: [1.1.1] 1.0.2
flixel-templates: 1.0.1 [1.0.2]
flixel-tools: [1.0.4] 1.0.2
flixel-ui: 1.0.1 [1.0.2]
flixel: [3.3.6]
haxelib_client: [3.1.0-rc.4]
hxcpp: [3.1.48] 3.1.21 3.1.39 3.1.22 3.0.2
hxlibc: [1.1.4]
lime: 0.9.5 2.0.1 0.9.6 0.9.4 [2.0.4]
nape: 2.0.13 2.0.9 [2.0.16]
nme: 4.0.2 [5.2.7] 5.0.29 5.1.8
openfl-bitfive: [2.1.6]
openfl-compatibility: [1.0.1]
openfl-html5-dom: [1.2.2] 1.2.0 1.2.1
openfl-html5: 1.0.2 1.1.0-beta 1.0.5 [1.4.2-beta]
openfl-native: 1.0.4 1.3.0 [1.4.0] 1.2.2 1.2.4
openfl-samples: [2.2.0] 1.0.0-rc.2 1.2.1 2.1.0
openfl-tools: 1.0.3 [1.0.10]
openfl: 2.2.1 1.2.3 1.3.0 [2.2.2] 2.1.7 1.2.2

**Comment by Gama11** [comment]
I can reproduce this on the lastest release, but the issue seems to be gone on dev.

```haxe
package;

import flixel.FlxSprite;
import flixel.FlxState;
import flixel.graphics.frames.FlxAtlasFrames;
import openfl.Assets;

class MenuState extends FlxState
{
	override public function create():Void
	{
		bgColor = 0xff4488cc;
		
		var sprite = new FlxSprite(0, 0);
		var frames = FlxAtlasFrames.fromTexturePackerJson(
			"assets/atlas/sprites.png", Assets.getText("assets/atlas/sprites.json"));
		sprite.frames = frames;
		
		sprite.animation.addByPrefix("idle", "player-idle-", 6);
		sprite.animation.play("idle");
		add(sprite);
	}
}
```
