### ISSUE TITLE
[Dev] Compile issues with new merges

### ISSUE THREAD

**Issue by MSGhero** [HaxeFlixel/flixel#1452]
Removing `FlxSprite#resetFrameBitmaps()` breaks 10 demos in the Travis build and also flixel-ui without any documented changes, also `FlxFrame#getBitmap()` was replaced and may break things.
@larsiusprime it fails in FlxUIButton for me.

**Comment by Beeblerox** [comment]
sorry about this.  forgot to update demoes, flixel-ui and changelog. will fix everything this week

**Comment by Beeblerox** [comment]
ok, i've updated broken demoes and updated changelog.
I removed `FlxFrame#getBitmap()` because frames don't store its images anymore. If you want to get frame's bitmapdata then you can call `FlxFrame#paint(bitmadDataToPaintOn, pointWhereToPaint, mergeAlpha)` where all arguments are optional.
If `bitmadDataToPaintOn` is null then new bitmapdata will be created
if `pointWhereToPaint` is null then frame will be painted in (0, 0)
`mergeAlpha` works the same as in `BitmapData#copyPixels()`
