### ISSUE TITLE
Code formatting abnormalities

### ISSUE THREAD

**Issue by MintPaw** [HaxeFlixel/flixel#1523]
I was looking through FlxVelocity.computeVelocity() today and I noticed some odd code formatting.

Like [here](https://github.com/HaxeFlixel/flixel/blob/dev/flixel/math/FlxVelocity.hx#L246) and [here](https://github.com/HaxeFlixel/flixel/blob/dev/flixel/math/FlxVelocity.hx#L250) where the lines are very similar but written it different formats.

Or like these two function headers [(1)](https://github.com/HaxeFlixel/flixel/blob/dev/flixel/math/FlxVelocity.hx#L235) [(2)](https://github.com/HaxeFlixel/flixel/blob/dev/flixel/math/FlxVelocity.hx#L271) Where the parameters are in different cases.

A last example is [here](https://github.com/HaxeFlixel/flixel/blob/dev/flixel/math/FlxPoint.hx#L424) where the author was using excessive whitespace on the lines previous but then decided to compress the next expression as possible.

All of the noted examples are within 40 lines of each other and don't seem like the result of different authors. Is there any reason for this? Do we have a defined guideline for style?

**Comment by Gama11** [comment]
There is a [style guide](http://haxeflixel.com/documentation/code-style/). It doesn't cover everything though and Flixel doesn't even follow everything mentioned there, especially the parameter casing thing - mostly because that's a huge pain to fix. There isn't auto-formatter tool for Haxe that I'm aware of.

Definitiely a result of a lot of different people working on the codebase.

**Comment by MSGhero** [comment]
There is an auto "throw an error if the formatting is off" that uses macros. I don't remember what it's called.

**Comment by Gama11** [comment]
Checkstyle? (https://github.com/adireddy/haxe-checkstyle) Someone suggested using that on travis a while ago. I'm not a huge fan of having builds fail because of cosmetic issues though, and I don't think travis has a concept of warnings.

Besides, to be able to use that, the code would have to be formatted consistently in the first place (see param names), without a formatter that still has to be done manually.

**Comment by MSGhero** [comment]
Idk about Travis, I was thinking once in a blue moon, someone runs that on flixel and fixes the formatting issues.

**Comment by Gama11** [comment]
Meh, seems like a waste of time, likely to introduce bugs too.

How about that someone writes a code formatter for Haxe instead? :)

**Comment by MSGhero** [comment]
Don't tempt me.

**Comment by MintPaw** [comment]
[This](https://github.com/HaxeFlixel/flixel/blob/7ec37e431349a40dc2aa9f0cb9228807fffb749c/flixel/FlxObject.hx#L556) is something else that bothers me, I'm not sure how exactly time inference works, the lack of definition makes this slower right?

**Comment by MSGhero** [comment]
It's slower for FD's type completion when it's trying to figure out what type your lazy ass meant. The compiler will (I think) type the easy inferences like the one you linked to, hard ones at runtime might take a microsecond longer maybe idk.

http://try.haxe.org/#73b59

**Comment by MSGhero** [comment]
@MintPaw I think you're thinking about it in terms of as3, where not typing something makes it an Object and doing the Object -> Type conversion takes time. Haxe has an [Unknown<> monomorph thing](http://haxe.org/manual/type-system-type-inference.html) rather than that.

**Comment by larsiusprime** [comment]
Yeah that will definitely be typed as a Float by the compiler. It happens at compile-time, not run-time, so it's identical to sticking a :Float in there at variable declaration.

**Comment by Gama11** [comment]
Leveraging type inference is good practice and makes the code more readable in a lot of situations.
