### ISSUE TITLE
FlxText word-wrap does not work properly with Chinese on android and ios

### ISSUE THREAD

**Issue by cutepig49** [HaxeFlixel/flixel#1551]
![default](https://cloud.githubusercontent.com/assets/3340057/8425440/61be9cbe-1f38-11e5-92ec-9144f5eaad35.PNG)
Instead of other words, a huge blank follows the first word.

**Comment by Gama11** [comment]
This issue is specific to iOS and Android, meaning it doesn't happen on other native targets (neko and cpp)?

Can you reproduce this outside of flixel? (pure openfl project with a regular `TextField` - that's what `FlxText` uses under the hood, there's a good chance this is an openfl issue)

What's the font file you're using?

**Comment by Gama11** [comment]
No followup here.
