### ISSUE TITLE
Fix unit tests on flash

### ISSUE THREAD

**Issue by Gama11** [HaxeFlixel/flixel#1552]
Since 7c0a0dc66f315ced29f9203ff26b045151e6b397, the font file is not present in the tests on flash, leading to some failures in `FlxTextTest` and `FlxButtonTest`.

**Comment by nazywam** [comment]
Any news on this? 
I cannot reproduce the FlxTextTest fail

**Comment by Gama11** [comment]
It's not exactly failing, but it's getting stuck in an endless loop.

**Comment by winterismute** [comment]
It seemed to be related to the constructor of FlxText, which threw an exception, and then the infinite loop was probably because what is in the before clause is retried before starting the test. Curiously, I could not make the same constructor throw an exception in a real program.
This https://github.com/HaxeFlixel/flixel/pull/1570 is a way to solve the problem which should also have no other side-effects, but maybe somebody else has a better way.

**Comment by Gama11** [comment]
>Curiously, I could not make the same constructor throw an exception in a real program.

Embedding assets via the `include.xml` file doesn't work with this method of building, which is likely the reason for that.
