### ISSUE TITLE
Sound stacking prevention

### ISSUE THREAD

**Issue by OpmSaitama** [HaxeFlixel/flixel#1620]
I think haxe flixel needs a function or modification of FlxG.play to cap how many sounds can play , for example if 10 enemies explode at once it should only play 2 or 3 explosions sounds at once.

FlxG.play("sound.ogg", volume,  limit);
limit - how many of the "sound.ogg" can be playing at once.

**Comment by Gama11** [comment]
You can already set `FlxG.sound.list.maxSize` - I think Mode does that somewhere. Of course, that wouldn't be sound-specific.

**Comment by OpmSaitama** [comment]
It needs to be sound specific because there if you are making a bigger game you will have so many sound effects. But only some of them will be "stacking" under certain conditions.

**Comment by MSGhero** [comment]
Another way to achieve this is to logarithmically add the sounds and then scale the sounds' volumes based off of that. That's how real life sound works. Idk if flixel should be the one to implement something along those lines, though.

**Comment by sruloart** [comment]
[Sound group](https://github.com/HaxeFlixel/flixel/pull/1316)
Sound group
[come on say it with me]
Sound group
Sound group
... :)

**Comment by Gama11** [comment]
@sruloart I thought of that when reading this issue, but that wouldn't really be sound-specific either.

**Comment by sruloart** [comment]
I don't understand the concept of controlling how many sounds are playing. How many? as many as you've previously decided. If you have an area in your game where too many sounds are playing at once then it's a design problem. For example, choosing multiple units in an RTS at once: you can have all of the units shout dozens "Ready!" at once, or you can just write something specific for that (play only the specific sound of random unit in the group).

There are no rules that would let you decide what sound should play or not, so maybe it wouldn't play the sound you prefer because you've already been passing your limit, resulting in a bad game experience. Adding a "playing" value to sounds (what's important to be played at this moment in time and place) is too cumbersome anyhow.

**Comment by OpmSaitama** [comment]
@sruloart  Imagine there are 10 enemies lines right next to eachother and each one has 1 health , and you shoot a piercing shot the sound stacking becomes so bad, but that's just one sound effect then there is also hitting sound. There could be also other cases that i didn't encounter yet but i think its a common issue everyone who makes a game will face at some point.

**Comment by sruloart** [comment]
I think my analogy is your analogy, and there's no unwanted stacking if you control the sounds playing via a sound group implementation. It's also a lot easier to give a relative "value" to a specific sound / another nested sound group within the group, using the group's members' index or a Map. 

I just don't see how arbitrarily limiting the number of sounds playing would fit any game at all. It's bad design, as in no design.

**Comment by OpmSaitama** [comment]
@sruloart i looked at the link for sound group, i didn't find it anywhere where is it. I'm using 3.3.11
FlxG.sound.addGroup() doesnt exist , tried importing FlxSoundGroup  , doesn't exist either.

**Comment by MSGhero** [comment]
@OpmSaitama that's a custom edit of the code, it doesn't exist on regular flixel.

The major downside to limiting the number of sounds is if an important sound should get played (dialogue, alert, etc), it may not end up getting played. It's best to modify the volumes of the already playing sfx, ignore duplicate sfx, or play a group version of that sfx rather than the solo version.

**Comment by Gama11** [comment]
Sound groups are now implemented, and you could probably implement something like this fairly easily with them. I don't think it should be part of the default implementation though.
