### ISSUE TITLE
Overlap2D runtime for HaxeFlixel

### ISSUE THREAD

**Issue by azakhary** [HaxeFlixel/flixel#1651]
Hi, I posted this on HaxeFlixel forums, but was advised to re-post here, I hope it's ok.

I am one of the developers behind Overlap2D (http://overlap2d.com/) which is an open source ui and level editor, and it's pretty language agnostic, meaning it just exports data into predefined format, and then provides different runtimes for all frameworks to load and render it. It is currently supporting libGDX only. And I wanted to add haxeflixel to the supported list. I checked and as far as I can tell there is no editor for this framework, so it might be handy? (Except tiled, but overlap2d supports both tiled and non tiled level structures)

If you have not seen o2d before - check out the website and video.

I have created an empty repo here: https://github.com/UnderwaterApps/overlap2d-runtime-haxeflixel
The documentation on overlap2d Data API is here: http://overlap2d.com/data-api-creating-custom-runtime/

The intention is to NOT port the our other libGDX runtime that is written in Java, but instead write a haxe runtime from scratch according to the specification. Problem is, I have never created a game with haxeflixel before, meaning, while I can dig in a lot, I still need your advice on "how to do it your way".

This includes many questions like should we have ECS or not e.t.c. I would be happy if there are people willing to help out with advice, or even more by contributing to the repo! 

Thanks a lot for reading.

**Comment by MSGhero** [comment]
So will this be a new UI lib in addition to a UI editor lib? Flixel has Flixel-UI lib already, and then there's haxeUI. If this is just an editor, could it be integrated with Flixel-UI? https://github.com/HaxeFlixel/flixel-ui/issues/5

**Comment by azakhary** [comment]
besides the UI, Overlap2D Editor provides content for rendering things like sprite animations, spine animations, spriter animations, particle effects, light effects, nine patch images, images, polygons, custom shaders. has support for physics, and providing custom tags and custom variables on items. There are things like layers and nested groups. So that's pretty much beyond UI. But it does have UI part as well (labels for example) so small part maybe can go with flixel-ui. Essentially Overlap2D as for making 2d levels for your game, be that a huge world with trees and effects, or be that tiled puzzle. I think this video demonstrates it best: https://www.youtube.com/watch?v=I0g-t0nZ-qE (this is an old video from old version though)

So let me know if flexel-ui can render this whole variety of things, if so we can totally use that.

**Comment by MSGhero** [comment]
Flixel and flixel-ui can already do most of that, with nape physics for any weird physics UI things. I would guess that most people are most interested in a UI editor over any new features, and making it use and export to Flixel-UI would be best for fitting people's current workflows. @larsiusprime

**Comment by azakhary** [comment]
There are several ways to approach this. And I am thinking, why not both. let me get into more detail.

1) If there is already a library that "reads" from certain data structure, that is awesome. what I can do is. create a plugin for overlap2d that exports things in "your way" All user will have to do, is to download the editor, download the plugin, make some stuff, and export, and then use already existing library that reads and renders that data.

2) Use existing output of o2d that does update with the editor, so we may have more features and stuff like that. And create the lib on based on flixel-ui (if it supports most of it). the lib will be reading the data, and using flixel-ui + adding physics + other missing parts if any, to make it a complete runtime.

The other thing to mention is. In our libGDX rutnime, we use Entity Component System, which is a good design choice. I've noticed this: https://github.com/nadako/Ash-HaXe which can be used for the runtime architecture (this is only of course if ECS is popular among HaxeFlixel users, if it's not there is no point)

**Comment by Ohmnivore** [comment]
Holy shit I'm really excited for this. I think this could give us Stencyl (http://www.stencyl.com/), but all the data is parsed from external files so within our source code we can access the parsed entities and do our own coding. I don't think we absolutely need to use flixel-ui, unless it's the only way to render according to specifications. My gut feeling is that vanilla haxeflixel is enough, provided we add some nine-slice handling and other additions.

My personal workflow at the moment is Ogmo Editor for levels, and well I need to make custom editors and/or fiddle with plain text files to get other data in, notably physics and UI. Overlap2D unifies all that into one (engine-agnostic) editor, so I dig that.

@azakhary I'll try to make a proof of concept

**Comment by azakhary** [comment]
I am ready to fully dive in, but I am very much not an expert here, you guys are. So I need all the help possible :) Would be cool to see proof of concept. And I was too thinking, that thing has to be light, so the more vanilla the better. We did same mistake with libGDX first by basing it on Scene2D-ui and then it was slow, so we remade it all in as simple way as possible.

This is entire specification with the benchmark: http://overlap2d.com/data-api-creating-custom-runtime/

Are there things that we "can't do" and will have to omit?

**Comment by azakhary** [comment]
Btw, other cool part for overlap2d is, that when you are making a big project, and need some kind of "very custom feature" that makes sense for your game only, you can make a "plugin" for it. This is what we do for our games.

**Comment by larsiusprime** [comment]
Hey there!

Has someone invited this guy to the Slack chat yet? Might be better to discuss some of this stuff in real time.

My understanding is that you can also use the Overlap2D as an in-game editor, right? In that case it might be better to implement its structure with HaxeUI rather than Flixel-UI. 

I'm quite proud of Flixel-UI, but it's not as full featured as HaxeUI and so we'd have to add features to support everything (scrollviews aren't supported yet for instance), whereas HaxeUI can do all that stuff now.

Flixel-UI is most useful for when you really need to be able to have all your UI elements as native Flixel objects rather than a big overlay on top of your flixel scene. I think in Overlap2D case, from what little I've seen in the video, that having a HaxeUI overlay on a flixel surface would probably be fine, as long as you had good callbacks between them. Let me introduce you to Ian Harrigan ... (Haxeui developer)

**Comment by sruloart** [comment]
* JSON is OK, but most of the flixel data is in xmls.
* Project data
 * pixelToWorld - we use pixels and zoom.
 * originalResolution - we use a specific resolution per target in the project's `project.xml`. Mobile targets don't have a specific resolution (width and height are zeroed-out).
 * resolutions - we don't have a resolution-dependent assets handling.
 * scenes - we don't have a scene, we have a FlxState which is a glorified FlxGroup. The objects (FlxObject for example) that are added to this group are rendered by a default camera (FlxCamera) using a bitmap (Flash, html5-canvas) or a tilesheet (native targets) solutions. There can be multiple states and multiple cameras of different sizes, the default camera can be replaced with another, and objects can be attached/detached to/from a specific camera with ease. Everything is very fluid. 
 * libraryItems - I guess a composite can be based upon FlxGroups.
* Scene
 * sceneName - we don't have that. This can be the name of the new FlxState class.
 * composite - see libraryItems.
 * lightSystemEnabled - we don't have light system yet.
 * ambient color - I'm not sure I understand this one.
 * physicsPropertiesVO - This would have to be something that extends the nape classes.
 * verticalGuides - don't have one of those.
 * horizontalGuides - don't have one of those.
* Scene Physics 
 * enabled - flixel doesn't have one variable for that, but the Nape classes does (requires initializing a FlxNapeSpace plugin).
 * gravityX/Y - both flixel and Nape should have no problem there. I'm not seeing the bodies data, lots of properties are missing here. 
* Composite
 * sImages - we don't have polygons and textures. We modify bitmapDatas and render them on screen, usually without any additional geometry information (besides matrices). 
 * sImage9patches - this can be done using flixel-ui or haxeUI. 
 * sComposites - see libraryItems.
 * sParticleEffects - flixel supports a popular format, shouldn't be too hard to utilize, I think.
 * sLights - this can be achieved using Nape.
 * sSpineAnimations - should be supported with the classes in the flixel-addons.
 * sSpriteAnimations - this is supported per FlxSprite or FlxTileSpecial.
 * layers - it would need to be a group with some extras (like `name` and `isLocked`).
* Main Item Structure 
 * uniqueId - there's an id var, but I don't know if that's 100% available.
 * itemIdentifier - no, we don't have that.
 * tags and customVars - we don't have these.
 * float x/y, scaleX/y, originXY, rotation - supported.
 * zIndex - can be achieved using the groups' indexes, but can get tricky since we don't a global z-ordering system.
 * layerName - would have to be added I suppose, to the modified FlxGroup.
 * tint - supported on all targets but html5-canvas.
 * shaderName - recently added to the dev branch.
 * shape - see sImages. 
 * physics - depends on the added properties I guess.

**Comment by azakhary** [comment]
@larsiusprime 
Would love to discuss realtime on slack, no inv so far :)

The only thing I want to mention that is important is, as you know overlap2d is still, well new, and there are some weak and strong points. And currently the game level design is stringer then UI.  Like for example we try to do everything with 9patches and grouping items, even if it's scroll bar, we make a group with the elements positioned absolutely, and then write script on top of it top make it a UI element. We do not have "layouting" (while I am always interested in adding that.) And we also do have labels. My point is. At this moment - more emphasis on level content, less on UI. (as far as editor functionality goes). You can combine things like animations, particle effects together, add tags and data on top of items. that is the main strong part now.

**Comment by azakhary** [comment]
It's more of this: https://www.youtube.com/watch?v=uFEhLDHr52I  then UI at this moment.

**Comment by larsiusprime** [comment]
Cool, that's good to know. What's your email? I think I have the power to invite people.

**Comment by azakhary** [comment]
azakhary [at] underwaterapps.com

**Comment by MSGhero** [comment]
What I didn't know we had a slack chat. Is this a flixel slack or a haxe one?

**Comment by SeiferTim** [comment]
@MSGhero It's for HaxeFlixel - get me or Lars your email.

**Comment by sruloart** [comment]
Here's the vid posted: https://www.youtube.com/watch?v=rqsLudrS8ko
Anyone's in for testing it out: https://github.com/UnderwaterApps/overlap2d-runtime-haxeflixel

**Comment by azakhary** [comment]
Okay so that skeletal version is kind of done and up (I submitted it to haxelib as well) We can probably move on and close this issue :) the github page for runtime also contains a wiki with docs.
