### ISSUE TITLE
FlxCamera with zoom < 1 and StageSizeScaleMode = broken clipping?

### ISSUE THREAD

**Issue by IBwWG** [HaxeFlixel/flixel#1718]
I have a window that's originally 640x480, with some content originally 640x100.  If I resize the window to 320x50 and set the main camera's zoom to 0.5, there does not appear to be a combination of camera.scroll.x/y and camera.width/height values that will make the 640x100 content take up the 320x50 window.

Unlike last time I am calling updateHitbox on everything :)

This is on HaxeFlixel dev branch updated today.

See screenshots here:

https://github.com/GimmickyApps/HaxeFlixelDevRepros/issues/6#issuecomment-181419201

Related to https://github.com/HaxeFlixel/flixel/issues/861 but I was trying to achieve this feature using workarounds in my game rather than digging into HF.  (Maybe the latter would be easier in the end?)

Likely related to #292 too, although not exactly the same thing, because #292 wasn't about resizing.
##

**Comment by GimmickyApps** [comment]
Just in case I'm failing to see something obvious, is it at all possible to currently make a game that supports both a custom variable aspect ratio (i.e. StageSizeScaleMode and manual layout) and high resolution displays?  It seems that if you support high resolution--in the sense of how Angry Birds is made, where it always looks sharp because they never allow zoom **>** 1--but then try to cram that into a 800x480 phone screen, you'll like have to zoom **<** 1 in order to see enough of your playing field for the game to be playable.  And then you run into this issue (and #1073 and so on.)  Am I trying to push HaxeFlixel beyond what it's meant for?  Is that a good thing?  Or is it just a bad fit for what I had in mind, and if I want to use HaxeFlixel I need to reimagine my design accordingly?

**Comment by Gama11** [comment]
Handling of zoom values < 1 was improved significantly by #2003 (and #292 is now closed), which is part of the 4.3.0 release, so there's a good chance this has been fixed in the meantime.
