### ISSUE TITLE
Refactor and fix FlxPath

### ISSUE THREAD

**Issue by IBwWG** [HaxeFlixel/flixel#1749]
- **Flixel version:** 4.0.0

`start()` is undocumented, but it'd be great to know:

1. Why does it take a nonoptional list of nodes?  From reading the docs it at first looks like you would add them via `add()`, `addAt()`, etc.  If those are only meant for adding nodes after `start()`ing maybe they should say so.  (But are they?)
1. Why doesn't it set `active` to true?  Is it meant that someone `start()`s a path and then sets `active` to true themselves?
1. It could maybe be made clear at the beginning that you attach a path to a FlxObject by setting the FlxObject's path property.  (I didn't know at first that they had such a property, so I was looking around the FlxPath API wondering how you're supposed to link the two.)
1. In what order should the `.path = myFlxPath`, `myFlxPath.start()`, and `myFlxPath.active=true` happen?
1. What units are `start()`'s `speed` parameter in?

**Comment by GimmickyApps** [comment]
OK, just from trying it out, for 4. I found that .path, then .active, then .start() works...

**Comment by winterismute** [comment]
Honestly, more than better documentation, I would say "refactor and fix flxPath". I mean, it has an empty constructor which does not even initialize a list of points, and then it's full of methods (head(), tail()) which do not check for null list (the base condition of the object), and other oddities. I actually wanted to do it myself one day.

**Comment by GimmickyApps** [comment]
Sounds good.

**Comment by winterismute** [comment]
I actually made something for this, it's here: https://github.com/HaxeFlixel/flixel/pull/1875
Honestly, I have realized I have messed up a bit, since I did start from the changes of https://github.com/HaxeFlixel/flixel/compare/issue-1749
but I did not integrate them directly, because I did not notice they were from the haxeFlixel tree, I thought they came from the fork of Beeblerox...
But it is the same rationale, in general making sure the _nodes list is ever empty (and therefore methods do not crash), the unit tests added (all failing before) should be enough to understand the changes.
