### ISSUE TITLE
Zoom on Android build "breaks" render

### ISSUE THREAD

**Issue by madnotdead** [HaxeFlixel/flixel#1766]
- **Flixel version:** 4.0.0
- **OpenFL version:** 3.6.0
- **Lime version:** 2.9.0
- **Affected targets:** Android 

________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxState;

class PlayState extends FlxState
{
	override public function create():Void
	{
	#if !mobile
			FlxG.mouse.visible = false;
		#end
		bgColor = 0xFF18A068;
		items =  new FlxTypedGroup<Item> ();
		enemies =  new FlxTypedGroup<Enemy> ();

		// Load the level's tilemaps
		_level = new TiledLevel(Reg.levels[Reg.level]);
		
		// Add tilemaps
		add(_level.backgroundTiles);
		
		// Add tilemaps
		add(_level.foregroundTiles);
		
		// Load player and objects of the Tiled map
		_level.loadObjects(this);
		
		add(items);
		add(enemies);
		add(exit);
		FlxG.camera.follow(player, FlxCameraFollowStyle.TOPDOWN,1);
        FlxG.camera.zoom = zoomValue;	
        add(player)
	}
}
```

```xml

Project.xml
<window width="640" height="480" fps="60" background="#000000" hardware="true" vsync="true" />
```
```haxe
class Main extends Sprite 
{
	var gameWidth:Int = 320; // Width of the game in pixels (might be less / more in actual pixels depending on your zoom).
	var gameHeight:Int = 240; // Height of the game in pixels (might be less / more in actual pixels depending on your zoom).
	var initialState:Class<FlxState> = MenuState; // The FlxState the game starts with.
	var zoom:Float =  -1; // If -1, zoom is automatically calculated to fit the window dimensions.
	var framerate:Int = 60; // How many frames per second the game should run at.
	var skipSplash:Bool = false; // Whether to skip the flixel splash screen that appears in release mode.
	var startFullscreen:Bool = true; // Whether to start the game in fullscreen on desktop targets
```
_______________________________

**Observed behavior:**

The render "breaks" on android build when zoom is set to 2.0 as it's shown in this image 
![screenshot_2016-03-05-16-37-30](https://cloud.githubusercontent.com/assets/4674391/13590257/1139c1c4-e4bd-11e5-9ab4-58531a763238.png)

**Expected behavior:**
This is the same build but with no zoom changed

![screenshot_2016-03-06-13-31-43](https://cloud.githubusercontent.com/assets/4674391/13590279/37190508-e4bd-11e5-9f02-74a02d4966cb.png)

I have had problems with zoom since i started using Haxeflixel, i don't know if i'm missing or misunderstanding something so any help would be appreciated.

**Comment by LastResortGames** [comment]
It is unfortunately a misunderstanding of how zoom actually works. I believe it is a decision that has gone back and forth in the past. It is not like a real life camera zoom where you look at a smaller area of the zone you are focused on. It is more like you are moving the camera itself further away or closer to you. You likely want to have your camera look at a smaller or larger area and THEN zoom in to make stuff appear larger/smaller.  

In my experience it has not worked as expected in any build but does it look as expected in other targets for you? It has been a few months for me so maybe it has been changed since then.

**Comment by madnotdead** [comment]
@LastResortGames The flash build doesn't have this problem 

![flash](https://cloud.githubusercontent.com/assets/4674391/13605687/8409f754-e527-11e5-92d2-dba58302a651.PNG)

And this is the html5 build

![html5](https://cloud.githubusercontent.com/assets/4674391/13605840/48166b96-e528-11e5-825e-e4909faa9b75.png)

It's really frustrating because i generally work with 16x16 sprites

**Comment by LastResortGames** [comment]
I notice that all screenshots you posted there are still only 16/17 tiles between the top and bottom of the screen despite the zoom setting. Are you sure you are actually setting the zoom in your second set of examples because they don't appear to be zoomed when comparing them to your Android expected behavior with no zoom.

And just to clarify, what is your end goal in this case? Do you want the number of visible tiles to double or halve?

**Comment by LastResortGames** [comment]
I just wrote up this off of the base flixel template. It appears that Android is acting consistently with other exports on my end with a mostly brand new setup. The resolutions are off slightly but that's to be expected. 

   	class MenuState extends FlxState
	{
		override public function create():Void
		{
			super.create();
			for (i in 0...32)
			{
				for (j in 0...32)
				{
					add(new FlxSprite(i * 16, j * 16,"assets/images/egg1.png"));
				}
			}		
			var play = new FlxSprite(100, 100);
			add(play);
			FlxG.camera.follow(play, FlxCameraFollowStyle.TOPDOWN,1);
			FlxG.camera.zoom = .5;   
		}

		override public function update(elapsed:Float):Void
		{
			super.update(elapsed);
		}
	}

And I got these results:

HTML5 (The default Haxeflixel icon didn't appear for whatever reason)

 ![html5zoom](https://cloud.githubusercontent.com/assets/8678606/13608377/91f08fa4-e522-11e5-8814-c8b097b11c49.PNG)

Neko

![nekozoom](https://cloud.githubusercontent.com/assets/8678606/13608382/9240bb50-e522-11e5-9346-359f7d06477b.PNG)

Android

![androidzoom](https://cloud.githubusercontent.com/assets/8678606/13608384/93226a82-e522-11e5-926c-d845ca6f5cdc.png)

(The egg image was used from http://opengameart.org/content/random-spritesheets)

**Comment by madnotdead** [comment]
@LastResortGames How is you project.xml and main.hx set up? I think something related to set up thos files is weird

**Comment by madnotdead** [comment]
@LastResortGames On desktop(flash/windows/neko) there's not change even if i set

`FlxG.camera.zoom = 2.0;`

But in Android it breaks the render... it's really weird

**Comment by LastResortGames** [comment]
It is completely unchanged from the default. I updated everything and literally ran 'flixel template' from the command line and only added that code above. It might be beneficial for you to try the same and see if it still acts like that on your end. 

The default Main.hx file now only has

	public function new()
	{
		super();
		addChild(new FlxGame(640, 480, MenuState));
	}

and the Project.xml appears the same too.


	<window width="640" height="480" fps="60" background="#000000" hardware="true" vsync="true" />

	
	<window if="html5" resizable="false" />

	
	<window if="desktop" orientation="landscape" fullscreen="false" resizable="true" />

	
	<window if="mobile" orientation="landscape" fullscreen="true" width="0" height="0" />

That is very strange. I can't help much more today. I might be able to fiddle around with it tonight though. I am checking again with the code you included relating to your Main.hx.

And did you change the FlxG.camera anywhere else in your codebase? Since it is a global variable.

**Comment by madnotdead** [comment]
@LastResortGames Let me change that, my Main.hx is derived from another project made with 3.2.0 but i migrated to 4.0.0 .

I'll give it a chance and keep you updated.

**Comment by LastResortGames** [comment]
Thanks. Hopefully somebody else can hop in to help as well. 

I have had my fair share of FlxCamera issues but they were typically consistent across exports. Your issue might actually be a proper bug if Android is acting in a completely different manner than the rest. It also might be a strange holdout from some 3.2.0 code or something as well.

**Comment by madnotdead** [comment]
@LastResortGames make the change and remembered why i have changed it to my own Main.hx

This happens in *flash* build with no zoom which is expected to happen

![flash2](https://cloud.githubusercontent.com/assets/4674391/13610342/00550b32-e53c-11e5-9dfa-59de25ade72e.PNG)

But this happens when zoom is added

![flash](https://cloud.githubusercontent.com/assets/4674391/13610363/19c0a11c-e53c-11e5-9c2a-9fd29cd915e2.gif)

The text which is setted with scrollfactor(0,0) dissapears and the camera doesn't follow the player. I don't know what to think... it's getting harder to resolve this.

**Comment by dstrekelj** [comment]
The result you've posted is consistent with what @LastResortGames described as the projection plane moving closer or farther away from the eye for an increasing or decreasing zoom factor.

For the sake of explanation, let's say you're in a box with a rectangular hole cut out of it right in front of your eyes (the _viewport_). You're staring at a screen (the _projection plane_) that your game is playing on.

In HaxeFlixel, the projection plane is by default set up in such a way that it perfectly fills your viewport. By zooming in, you're actually bringing the projection plane closer to your viewport. Everything seems much larger and "cut off". By zooming out, you're doing the opposite - moving the projection plane farther away from your viewport. Everything seems much smaller and boxed in.

With that in mind, let's briefly discuss the following:

> The text which is setted with scrollfactor(0,0) dissapears and the camera doesn't follow the player. I don't know what to think... it's getting harder to resolve this. - @madnotdead 

The UI text doesn't exactly _disappear_ - it still exists, but outside of the bounds of your viewport. Remember that you've brought the projection plane closer to you, sacrificing perspective for detail. Here are two common ways of dealing with this:

* Reposition the UI so that it is drawn inside of the viewport bounds.

* Draw the UI on a separate camera and overlay it over the main one.

Note that the scroll factor isn't the issue here because the camera isn't _moving_. What the scroll factor affects is how the sprite moves with the camera as the camera scrolls. A scroll factor of two means that the sprite moves in the direction of the camera _twice as fast as the camera_. A scroll factor of one means that it follows the camera with a 1:1 ratio. A scroll factor of zero means that the sprite remains stationary on the screen _despite the scrolling camera_. This is, of course, commonly used for UI elements.

Because the projection plane is so close to the viewport, you need a way for the camera to keep the player in focus as he moves around the game world. To do that, you only need to tell the camera what sprite to follow (and, optionally, _how_ to follow). This is done with `FlxG.camera.follow()`. There is a good demo showcasing various camera follow types [here](http://haxeflixel.com/demos/FlxCamera/).

What the different follow types do is, essentially, define a specific _deadzone_. This is a rectangular boundary within which the sprite can move freely without the camera following him. Reaching the bounds of the deadzone then repositions the camera accordingly to keep the player from leaving the deadzone. This is typically done within camera _scroll bounds_ - another rectangular boundary - that defines the area within which the camera can move.

I feel like I might have missed the point of your post, nevertheless I hope I managed to clear up some things about FlxCamera.

**Comment by madnotdead** [comment]
@dstrekelj Wow, that's a wonderful explanation! I knew i was missing something thanks for pointed it out. 

In my other game i resolve it by using a HudCam and a GameCam, one for the hud and the other to follow the player. I thought it was an 3.2.0 issue not an misuse of camera properties. 

But here's the thing, even if i change the zoom and set the camera to follow the player i doesnt. It just stay in the middle of the screen.The player goes arround the screen, outside the viewport limit but the camera just stays still. I uploaded a gif in my previous post with this behaviour.

For your own experience how should i approach this? My idea was to zoom the game and follow the player if i show all the map it loose its purpose.

**Comment by LastResortGames** [comment]
@madnotdead Your viewport can't see the whole scene so it only appears that the player is leaving the point that the camera should be following but the camera still can see the whole scene. It does not need to scroll at all because from its point of view the player is still inside its view. If your camera was looking at a smaller portion of the world it should scroll with the character.

**Comment by madnotdead** [comment]
@LastResortGames Got it! I was suspecting this. So my whole level is 640x480 as windows size, if i zoom to 2 I should change camera viewport? Something like 640/zoomvalue and 480/zoomvalue?

**Comment by dstrekelj** [comment]
@madnotdead The way I handled this was to increase the scroll bounds by the amount of "projection plane real-estate" placed outside of the viewport by the action of zooming in.

Here's a (pseudo)code sample.

```haxe
// New zoom value
var zoom = 2;
// Percentage of aforementioned clipped "projection plane real-estate"
var factor = (zoom - 1) / (zoom * 2);
// Differences along X and Y
var dx = FlxG.width * factor;
var dy = FlxG.height * factor;
// The observable slice of the game world (top-left corner position and dimensions)
var worldX = 0;
var worldY = 0;
var worldWidth = FlxG.width;
var worldHeight = FlxG.height
// Update zoom
FlxG.camera.zoom = zoom;
// Update scroll bounds
FlxG.camera.setScrollBounds(worldX - dx, worldY - dy, worldWidth + dx, worldHeight + dy);
```

Note that the above only works if `zoom >= 1`. For context, see [this post](https://groups.google.com/d/msg/haxeflixel/BMohE0iWngw/nQJZjO9hDgAJ) on the HaxeFlixel Google group.

**Comment by madnotdead** [comment]
@dstrekelj Nice post, i'll take a deeper look to your class. Now i'll try the factor value to see how it works,

**Comment by madnotdead** [comment]
UPDATE 

@dstrekelj i tested the snippe you suggest and get this behaviour

![flash_1](https://cloud.githubusercontent.com/assets/4674391/13657546/e92ff278-e64e-11e5-9fd9-7ec98d784471.gif)

It just worked on left upper corner but not in the oposite... As you mention i took a look on the FlxCamera demo , and after you explained, I understood how the zoom is set and fixed on the demo so i added this snippe to my Playstate.hx. This was the result


```
public function setZoom(zoom:Float):Void
	{
		
		var worldX = 0;
		var worldY = 0;
		var worldWidth = FlxG.width;
		var worldHeight =  FlxG.height;
		
		if (zoom < .5) zoom = .5;
		if (zoom > 4) zoom = 4;
		
		zoom = Math.round(zoom * 10) / 10; // corrects float precision problems.
		
		FlxG.camera.zoom = zoom;
		
		#if TRUE_ZOOM_OUT
		zoom += 0.5; // For 1/2 zoom out.
		zoom -= (1 - zoom); // For 1/2 zoom out.
		#end
		
		var zoomDistDiffY;
		var zoomDistDiffX;
		
		
		if (zoom <= 1) 
		{
			zoomDistDiffX = Math.abs((worldX + worldWidth) - (worldX + worldWidth) / 1 + (1 - zoom));
			zoomDistDiffY = Math.abs((worldY + worldHeight) - (worldY + worldHeight) / 1 + (1 - zoom));
			#if TRUE_ZOOM_OUT
			zoomDistDiffX *= 1; // For 1/2 zoom out - otherwise -0.5 
			zoomDistDiffY *= 1; // For 1/2 zoom out - otherwise -0.5
			#else
			zoomDistDiffX *= -.5;
			zoomDistDiffY *= -.5;
			#end
		}
		else
		{
			zoomDistDiffX = Math.abs((worldX + worldWidth) - (worldX + worldWidth) / zoom);
			zoomDistDiffY = Math.abs((worldY + worldHeight) - (worldY + worldHeight) / zoom);
			#if TRUE_ZOOM_OUT
			zoomDistDiffX *= 1; // For 1/2 zoom out - otherwise 0.5
			zoomDistDiffY *= 1; // For 1/2 zoom out - otherwise 0.5
			#else
			zoomDistDiffX *= .5;
			zoomDistDiffY *= .5;
			#end
		}
		
		FlxG.camera.setScrollBoundsRect(worldX - zoomDistDiffX, 
							   worldY - zoomDistDiffY,
							   (worldWidth + Math.abs(worldX) + zoomDistDiffX * 2),
							   (worldHeight + Math.abs(worldY) + zoomDistDiffY * 2),
							   false);
	}
```
________________________________

This was the behavior that i got

![flash_2](https://cloud.githubusercontent.com/assets/4674391/13657677/c94abbc2-e64f-11e5-82ac-47018f7b9c01.gif)


Now I have to realize how to set the 'HudCamera'so my hud would be visible for the player after the zoom is added

**Comment by dstrekelj** [comment]
@madnotdead Glad to see you've made progress!

Setting up the HUD (UI) camera is essentially the same as setting up the main game camera. Just draw the UI elements and create a new camera that will follow them.

The problem you might come across is one of _visibility_. For instance, drawing the UI somewhere within the traversable game world will mean that it will probably be visible on your main camera _as well_ as your dedicated UI camera when the player reaches that part of the world.

Two common ways to remedy that are:

* Drawing the UI outside of the game world

* Drawing the UI to the UI camera _only_

If you look at the [FlxCamera demo code](https://github.com/HaxeFlixel/flixel-demos/blob/dev/Features/FlxCamera/source/HUD.hx), you'll notice that it uses the former - it creates the UI with an initial offset of 10000 units along the x-axis to ensure it is never reached by the player. Note the use of an exposed "container" sprite - in this case `background` - so that the camera has something to follow.

**Comment by madnotdead** [comment]
@dstrekelj After some test i try the camera demo aproach, this was the result

![flash_3](https://cloud.githubusercontent.com/assets/4674391/13693086/3957755a-e726-11e5-939a-13eafae8de0f.gif)


I'm not happy with this because i have to add a background sprite, the black one with less alpha, i've seen haxeflixel games without this. It's quite frustrating not to have a nice example but aproachs that works on custom cases.

When you said **Drawing the UI to the UI camera only** what were you suggesting?

**Comment by dstrekelj** [comment]
@madnotdead The background sprite does _not_ need to be visible at all. In this case, it only needs to _exist_ so that the FlxCamera has a UI element to follow. Alternatively, you can do without the background sprite and manually set up your UI camera to look at the UI. This requires a little bit more work, though. For reference, you can look at the way `FlxCamera.follow()` works.

To briefly answer your question: HaxeFlixel keeps track of an array of created FlxCamera objects. This array is made accessible through a `cameras` property in FlxG and FlxSprite, if I'm not mistaken. Every FlxSprite gets a copy of that array on creation (or some iteration of it, depending on when the sprite is created). It is, in essence, a list of views to draw that sprite to.

What you can do is create a separate UI camera after you create the UI. Then, you set the UI's cameras array to just the one UI camera - this ensures the UI isn't drawn in other views. When creating the UI camera you get to position it on the screen. Keep in mind that the order of cameras in `FlxG.cameras` matters - the last camera in the array gets drawn _last_.

With that in mind, the UI camera should be the last camera in the `FlxG.cameras` array to ensure it is drawn above the game camera. If the UI is transparent, you must also make sure to disable drawing anything akin to a FlxBackdrop to the UI camera, and also ensure that the camera's image buffer is reset to a fully transparent clear color.

I'm in a bit of a rush so I can't go into greater detail, but if you have any questions feel free to let me know.

**Comment by madnotdead** [comment]
@dstrekelj i forgot to add that the background image which i follow with the camera is transparent.

`background = new FlxSprite(x, 0);
		background.makeGraphic(width, height, FlxColor.TRANSPARENT);
		add(background);`

And in my PlayState.hx i follow like this

`  
hud = new Hud();
		add(hud);

		#if TRUE_ZOOM_OUT
		hudCam = new FlxCamera(440 + 50, 0 + 45, hud.width, hud.height); // +50 + 45 For 1/2 zoom out.
		#else
		hudCam = new FlxCamera(0, 0, FlxG.width, hud.height);
		#end
		hudCam.zoom = 1; // For 1/2 zoom out.
		hudCam.follow(hud.background, FlxCameraFollowStyle.NO_DEAD_ZONE);
		hudCam.alpha = .5;
		FlxG.cameras.add(hudCam);`


So i undestand that the black overlay the hud has it's because of the background color of the state.

**Comment by dstrekelj** [comment]
Your understanding is correct! Try using something like `hudCam.bgColor.alpha = 0` to remove the black "overlay". This will make the camera background color transparent. Note that it works in conjunction with `hudCam.alpha`, so anything drawn to that camera will still be affected by the camera's alpha property.

**Comment by madnotdead** [comment]
Finally, now everthing work as expected even in android!

This is the flash

![flash_4](https://cloud.githubusercontent.com/assets/4674391/13710386/ed65beb4-e797-11e5-8df6-f9f9420750e2.gif)

And this is the android one

![screenshot_2016-03-11-14-39-29](https://cloud.githubusercontent.com/assets/4674391/13710393/fa4b91bc-e797-11e5-9615-5b5a3d8770d3.png)

The only thing that bothers me is the **black space in the borders**, but i think this is related to the 4:3 resolution i'm using. In android i have to set the virtual pad's camera to be the hudcamera because if not the buttons where not displayed. I think they are a little small but haven't digged too much in it.

Well, thanks @dstrekelj for everything, your advices were very importan to accomplish my goal. @larsiusprime thanks for the retweet it gaved this issue the visibility needed.

**Comment by madnotdead** [comment]
Unfortunably i've found a new issue. Originally the game size was **640x480**, i tried to change it to an **16:9** resolution like **640x360** but with this change the camera broke again, any advice about this? Its really strange because the new camera viewport is calculted with the width and height from FlxG. This is the current behaviour:

![flash_5](https://cloud.githubusercontent.com/assets/4674391/13713255/d9c72190-e7a6-11e5-88e9-1015bc3974e6.gif)

**Comment by dstrekelj** [comment]
I can't say for sure without seeing some code, but I would start debugging by taking a look at how the camera scroll bounds are set.

It's getting a bit late on my end, so I'll see if I can create a minimal example tomorrow.

**Comment by dstrekelj** [comment]
@madnotdead, as promised, here's a minimal working example. I was as explicit as possible where I found that to be important.

I'm using:

```
flixel 4.0.0
lime 2.9.0
openfl 3.6.0
```

A new, empty project was created with `flixel tpl`. The project's XML file was left unchanged. The classes are defined as follows.

**Main.hx**

```haxe
package;

import flixel.FlxGame;
import openfl.display.Sprite;

class Main extends Sprite
{
	public function new()
	{
		super();
		addChild(new FlxGame(640, 360, PlayState));
	}
}
```

**PlayState.hx**

```haxe
package;

import flixel.FlxG;
import flixel.FlxSprite;
import flixel.FlxState;
import flixel.graphics.FlxGraphic;
import flixel.math.FlxRect;
import flixel.util.FlxColor;

using flixel.util.FlxSpriteUtil;


class PlayState extends FlxState
{
	// Reference to player object
	var player : Player;
	// The traversable world boundaries
	var world : FlxRect;
	
	override public function create():Void
	{
		super.create();
		
		// Define the traverable world boundaries
		world = FlxRect.get(0, 0, 640, 360);
		
		/**
		 * What follows is a horrendous, "quick and dirty" way of 
		 * creating a reference grid. Avoid at all costs. Note that
		 * increasing the world bounds will cause a significant
		 * performance decrease because of this mess.
		 */
		
		var box = new FlxSprite(0, 0);
		box.makeGraphic(10, 10, FlxColor.GRAY, true);
		box.drawLine(0, 0, 0, 10);
		box.drawLine(0, 10, 10, 10);
		box.drawLine(10, 10, 10, 0);
		box.drawLine(10, 0, 0, 0);
		
		for (row in 0...Std.int(world.width / 10))
		{
			for (column in 0...Std.int(world.height / 10))
			{
				add(new FlxSprite(row * 10, column * 10).loadGraphicFromSprite(box));
			}
		}
		
		// Add player to the state
		player = new Player();
		add(player);
		
		// Bring the camera's projection closer to the viewport
		FlxG.camera.zoom = 4;
		// Have the camera follow the player tightly
		FlxG.camera.follow(player, flixel.FlxCamera.FlxCameraFollowStyle.LOCKON);
		
		/**
		 * Specify the boundaries of the camera's movement within the
		 * game world. By bringing the camera's projection of the world
		 * closer to the viewport, we limited the visible area of the
		 * projection. The "clipped" area depends on the zoom factor.
		 * But, because we're using a factor of two, we can see that
		 * our viewport will be looking at a projection that is half
		 * its original size - as it was shrunk from all sides (top,
		 * right, left, and bottom) by a quarter of the viewport (the
		 * screen) dimensions.
		 */
		
		FlxG.camera.setScrollBoundsRect(
		// Give the camera extra breathing room to the left
			world.x - FlxG.width / 4,
		// Give the camera extra breathing room to the top
			world.y - FlxG.height / 4,
		// We do it twice here to compensate for the previous offset
			world.width + FlxG.width / 4 + FlxG.width / 4,
		// Again, we're also compensating for the previous offset
			world.height + FlxG.height / 4 + FlxG.height / 4
		);
	}

	override public function update(elapsed:Float):Void
	{
		super.update(elapsed);
		
		/**
		 * The following limits the player's movement to the world
		 * boundaries.
		 */
		
		if (player.x < world.x) player.x = world.x;
		if (player.x > world.width - player.width) player.x = world.width - player.width;
		if (player.y < world.y) player.y = world.y;
		if (player.y > world.height - player.height) player.y = world.height - player.height;
	}
}

class Player extends FlxSprite
{
	public function new()
	{
		super(0, 0);
		this.makeGraphic(20, 20, FlxColor.BLUE);
	}
	
	override public function update(elapsed:Float):Void
	{
		super.update(elapsed);
		
		if (FlxG.keys.pressed.A)	this.x -= 2;
		if (FlxG.keys.pressed.D)	this.x += 2;
		if (FlxG.keys.pressed.S)	this.y += 2;
		if (FlxG.keys.pressed.W)	this.y -= 2;
	}
}
```

There shouldn't be anything unfamiliar here if I've managed to explain myself well up until this point. The takeaway should be that the camera scroll bounds are used here to make up for the visible areas cut off by the act of zooming in.

**Comment by dstrekelj** [comment]
[](https://i.gyazo.com/9eff0001162b94b280400a87b729de83.mp4)

**Comment by madnotdead** [comment]
@dstrekelj Wow! That's great, nice demo. I see what you were saying, sadly i haven't been able to fix mine but i have compared both examples and the result suprise me, really

this is my camera's scrolls

![scroll_mine](https://cloud.githubusercontent.com/assets/4674391/13724969/4c99d514-e874-11e5-814a-1d64b691843d.png)

And this is yours

![scroll_](https://cloud.githubusercontent.com/assets/4674391/13724972/52e8284e-e874-11e5-997b-cb10c996c246.png)


They are not so different. The interesting part is that my maxScrollY is higher than yours. I have to go now but later i will make some tests. Thanks for the demo!

**Comment by dstrekelj** [comment]
You should be getting whole even numbers if you're zooming in by two at a resolution of 640 x 360. I suggest revisiting the code that is setting the values of the scroll bounds.

**Comment by madnotdead** [comment]
@dstrekelj yes, the zoom variable was set 2.2, that was the reason. After some research i discover that i was wrong with the world size. I'm using a tiled map as level and it's bigger than my windows. The map was 640*480 but i was setting the world width as the FlxG.width which was not correct. After i changed it this was the result:

![flash_7](https://cloud.githubusercontent.com/assets/4674391/13757949/990514a8-ea05-11e5-8652-0fa0f9fb962e.gif)

Then I try your solution with different result

![flash_8](https://cloud.githubusercontent.com/assets/4674391/13758083/50b7b556-ea06-11e5-92f6-56e683f2a760.gif)


And it works in the android build

![screenshot_2016-03-14-16-39-43](https://cloud.githubusercontent.com/assets/4674391/13758089/58463f54-ea06-11e5-80da-02b6f514eccd.png)


This is the code i use to calculate the zoom but only works for 4:3 resolutions

`public function SetZoom(zoom:Float):Void
	{
		
		var worldX = 0;
		var worldY = 0;
		var worldWidth = _level.fullWidth;
		var worldHeight = _level.fullHeight;
		
		if (zoom < .5) zoom = .5;
		if (zoom > 4) zoom = 4;
		
		zoom = Math.round(zoom * 10) / 10; // corrects float precision problems.
		
		FlxG.camera.zoom = zoom;
		
		#if TRUE_ZOOM_OUT
		zoom += 0.5; // For 1/2 zoom out.
		zoom -= (1 - zoom); // For 1/2 zoom out.
		#end
		
		var zoomDistDiffY;
		var zoomDistDiffX;
		
		
		if (zoom <= 1) 
		{
			zoomDistDiffX = Math.abs((worldX + worldWidth) - (worldX + worldWidth) / 1 + (1 - zoom));
			zoomDistDiffY = Math.abs((worldY + worldHeight) - (worldY + worldHeight) / 1 + (1 - zoom));
			#if TRUE_ZOOM_OUT
			zoomDistDiffX *= 1; // For 1/2 zoom out - otherwise -0.5 
			zoomDistDiffY *= 1; // For 1/2 zoom out - otherwise -0.5
			#else
			zoomDistDiffX *= -.5;
			zoomDistDiffY *= -.5;
			#end
		}
		else
		{
			zoomDistDiffX = Math.abs((worldX + worldWidth) - (worldX + worldWidth) / zoom);
			zoomDistDiffY = Math.abs((worldY + worldHeight) - (worldY + worldHeight) / zoom);
			#if TRUE_ZOOM_OUT
			zoomDistDiffX *= 1; // For 1/2 zoom out - otherwise 0.5
			zoomDistDiffY *= 1; // For 1/2 zoom out - otherwise 0.5
			#else
			zoomDistDiffX *= .5;
			zoomDistDiffY *= .5;
			#end
		}
		
		FlxG.camera.setScrollBoundsRect(worldX - zoomDistDiffX, 
							   worldY - zoomDistDiffY,
							   (worldWidth + Math.abs(worldX) + zoomDistDiffX * 2),
							   (worldHeight + Math.abs(worldY) + zoomDistDiffY * 2),
							   true);
							   
		FlxG.watch.add(FlxG.camera, "minScrollX", "minScrollX");
		FlxG.watch.add(FlxG.camera, "minScrollY", "minScrollY");
		FlxG.watch.add(FlxG.camera, "maxScrollX", "maxScrollX");
		FlxG.watch.add(FlxG.camera, "maxScrollY", "maxScrollY");
	}`


For the moment and just because i generally use zoom = 2 i'm going to go with your solution. This is getting really tired. I'll dig again when i need it.

Thanks for the tips and your time :D

**Comment by Gama11** [comment]
It seems like this is solved / there wasn't actually a bug here.
