### ISSUE TITLE
Mouse cursor missing after using debug console

### ISSUE THREAD

**Issue by GimmickyApps** [HaxeFlixel/flixel#1775]
- **Flixel version:** dev
- **OpenFL version:** 3.6.0
- **Lime version:** 2.9.0
- **Affected targets:** flash debug

________________________________

**Steps to reproduce**
1. press ~ to bring up the debug console
1. press tab OR click in the console text field so you can type
1. press ~ to hide the debug console

**Observed behavior:** mouse cursor is permanently gone
**Expected behavior:** mouse cursor should be unaffected by this

**Comment by Gama11** [comment]
Huh... I don't think this has always been the case, must've broken at some point.

**Comment by larsiusprime** [comment]
I've noticed this a whole bunch! I thought I was being crazy!

**Comment by Gama11** [comment]
Looks like this has actually been happening for a while (at least 3.3.12 - unfortunately it's difficult to go back further than that because of breaking changes in both OpenFL and Haxe).

**Comment by Gama11** [comment]
There are actually multiple different issues here. One of them is the fact that the debugger always sets `useSystemCursor` to `false` when it loses focus to revert to the Flixel cursor - regardless of what value `useSystemCursor` had previously, potentially overriding the user's changes.

The simplest solution would be to get rid of this "switch between Flixel and system cursor" behavior (always seemed somewhat annoying to me anyway) and render the Flixel cursor on top of the debugger. However, that's not really an option, since the mouse cursor still needs to work when the game is paused via the VCR buttons in the debugger - since that pauses the updating of `FlxG.inputs` as well, the cursor would currently stop moving.

**Comment by GimmickyApps** [comment]
For the record, I don't use any custom cursor...maybe I misunderstood though

**Comment by adrianulima** [comment]
could store all user's mouse properties when open the console and restore when close?

**Comment by Gama11** [comment]
That's more or less what I've done in a commit I haven't pushed yet.. Not when closing the debugger though, but when any debugger component loses focus.
