### ISSUE TITLE
crash using animation.addByPrefix()

### ISSUE THREAD

**Issue by GimmickyApps** [HaxeFlixel/flixel#1786]
- **Flixel version:** dev
- **OpenFL version:** 3.6.0
- **Lime version:** 2.9.0
- **Affected targets:** flash, probably all

________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxState;

class PlayState extends FlxState
{
	var leftFighter:FlxSprite;
	override public function create():Void
	{
		super.create();
		leftFighter = cast add(new FlxSprite().loadGraphic(AssetPaths.katatedoriShihonage_000__png, true, 452, 414, true));
		leftFighter.animation.addByPrefix("Katatedori Shihonage", "assets/images/katatedoriShihonage_", 21, true);
		leftFighter.animation.play("Katatedori Shihonage");
	}
}
```

________________________________

**Observed behavior:** 

```
TypeError: Error #1009: Cannot access a property or method of a null object reference.
	at StringTools$/startsWith()[C:\HaxeToolkit\haxe\std\StringTools.hx:142]
	at flixel.animation::FlxAnimationController/findByPrefix()[C:\HaxeToolkit\haxe\lib\flixel\git\flixel\animation\FlxAnimationController.hx:719]
	at flixel.animation::FlxAnimationController/addByPrefix()[C:\HaxeToolkit\haxe\lib\flixel\git\flixel\animation\FlxAnimationController.hx:452]
at (my playstate)
```
Or, if I leave off the `loadGraphic()` call, the flixel debugger says `[WARNING] No animation called "Katatedori Shihonage"` and I get a placeholder image, but otherwise no clues are given from `addByPrefix()` as to what I might be doing wrong.

**Expected behavior:**  Animation loaded and played...

________________________________
I had been loading frames like this, with one big sprite sheet:

```haxe
	override public function create():Void
	{
		super.create();
		leftFighter = cast add(new FlxSprite().loadGraphic(AssetPaths.katatedoriShihonage__png, true, 452, 414, true));
		var frames:Array<Int> = [];
		for (i in 0...45)
			frames.push(i + 1);
		leftFighter.animation.add("Katatedori Shihonage", frames, 21, true);
		leftFighter.animation.play("Katatedori Shihonage");
```

But the problem is, when I have as many frames as I plan to in the end, they will not fit on a single sprite sheet without hitting the common 4096x4096 texture size limit, even if I use multiple rows and columns rather than a single strip.  So I wanted to load them individually from files suffixed with _000, _001, _002, and so on.  From [the documentation](https://github.com/HaxeFlixel/flixel/blob/fc4abe05e19e13992f133b299d6cf36dfd013eed/flixel/animation/FlxAnimationController.hx#L437) for `addByPrefix()` it sounded like that's exactly what that's for, individual PNG files for each frame, named this way:

```
	/**
	 * Adds a new animation to the sprite.
	 * 
	 * @param	Name		What this animation should be called (e.g. `"run"`).
	 * @param	Prefix		Common beginning of image names in atlas (e.g. `"tiles-"`).
	 * @param	FrameRate	The speed in frames per second that the animation should play at (e.g. `40` fps).
	 * @param	Looped		Whether or not the animation is looped or just plays once.
	 * @param	FlipX		Whether the frames should be flipped horizontally.
	 * @param	FlipY		Whether the frames should be flipped vertically.
	 */
```

I'm likely doing it wrong, but I hope this functionality is actually supported...in this case maybe we can touch up the documentation a tiny bit for future newcomers.

**Comment by GimmickyApps** [comment]
I see that Atlases probably exist for this, but it's also not very clear from the docs how to use them.  I guess I load frames like this:

```haxe
		for (i in 0...45) {
			frames.push(i + 1);
			var name = "assets/images/katatedoriShihonage_" + pad(cast (i + 1));
			atlas.addNode(name);
		}
```

But then how does addByPrefix know which atlas to take from?

**Comment by GimmickyApps** [comment]
After some poking around and guessing, I came up with this, which works.  Not sure if it's going to be efficient or what, but at least it's animating for now:

```haxe
		leftFighter = cast add(new FlxSprite(300, 100));
		var frames:Array<Int> = [];
		var ffc = new FlxFramesCollection(null);
		for (i in 0...45) {
			frames.push(i + 1);
			var name = "assets/images/katatedoriShihonage_" + pad(cast i) + ".png";
			ffc.pushFrame(FlxImageFrame.fromImage(name).frame);
		}
		leftFighter.frames = ffc;
		leftFighter.animation.add("Katatedori Shihonage", frames, 21, true);
		leftFighter.animation.play("Katatedori Shihonage");
```

**Comment by MSGhero** [comment]
I've never seen those before, so they probably don't matter, but I would choose ATLAS. 

Yeah, you have to have a frame collection added to the Sprite in order to animate it in any case. You don't have to make your own, you use a tool that makes a spritesheet and gives you a data file, and then you let flixel do the work for you. I think there's an example in demos.

**Comment by GimmickyApps** [comment]
I can't afford a pay tool right now, which I believe TexturePacker is...isn't that what the atlas class is for?

But it's a bit moot, the whole problem in the first place is that a packed texture won't work in this case because it would exceed the maximum texture size.  So I need to load individual frames from individual files, but I still want to leverage flixel's animation system if possible.

**Comment by MSGhero** [comment]
The point of the atlas class is so that you can use texture packer or other tools to make your life easy. There's a free version and a paid version, and there are options to export multiple sheets. You could also make several sheets yourself and group the things that need to be together.

I have over 1500 image files, so I'm not going to manually assemble a spritesheet.

**Comment by GimmickyApps** [comment]
I don't think I'm communicating very clearly.  I would never manually assemble a sprite sheet either.  But in this case, a sprite sheet doesn't help me, because it won't fit in memory.  My video card has a max texture size of 4096x4096.  When my animation goes up to 100 frames, it doesn't matter how you pack them, a 452x415 sprite cannot fit in there 100 times.

**Comment by MSGhero** [comment]
Then I think a better issue would be a frame collection class that can have multiple source images, so that you could use texture packer to export multiple spritesheets of whatever size you want. 

Plus, TP has a crop feature, downscaling, and auto detects when you have duplicates. If your sprites are that huge and you can't crop anything from them and don't have duplicates and can't downscale them, that feels like you're doing something wrong on the art side. Maybe your project is the one that requires that.

**Comment by GimmickyApps** [comment]
Yes, it's one that requires that.  And as I posted, it actually does work OK, without sprite sheets.  The feature you're talking about, multiple source spritesheets, is probably even possible already with flixel as-is, but I'm not sure.

There are two issues with flixel, 1--the docs are a bit difficult to navigate here.  2--the crashing bug I found.

**Comment by MSGhero** [comment]
It's not a bug, though. Maybe it deserves a specific error message, but all of the animation functions require `frames` to already be defined, otherwise they don't make sense to use.

There isn't a way to have multiple source images, I think it's already an issue or a side project someone tried to work on. You could have multiple and stitch them together in flixel and offset the second image's x coordinates in the data file, but no one wants to do that.

**Comment by GimmickyApps** [comment]
I would say you shouldn't be able to make the library crash, but maybe that's not the standard here.

If they require that, it might be good to say so somewhere.  Things making sense if you're used to them don't help someone who is not used to them, and therefore reads the docs.

You can have multiple source images: I just posted the code I used, which works, without modifying flixel.  Judging by the myriad frame/anim related classes and their functions, I think that you could probably rig it up to use multiple source sprite sheets as well, but I could be wrong.  I'll try to cross that bridge if I come to it, and if so I'll post any code here that ends up working.

**Comment by MSGhero** [comment]
The code snippet at the beginning is adding a single image and expecting it to become a full `FlxFrameCollection`, which shouldn't and doesn't work since there's no spritesheet or data file. Using `loadGraphic` implies that you don't want to use a spritesheet. And I meant multiple spritesheets, that functionality doesn't exist yet.

@Gama11 what do you think? Should the `frames` generated from `loadGraphic` be given some default string to fill the `name` property so this line doesn't crash? Or should we check for if the name is null and handle that here? https://github.com/HaxeFlixel/flixel/blob/dev/flixel/animation/FlxAnimationController.hx#L719

**Comment by Gama11** [comment]
A null-check can't really hurt.
