### ISSUE TITLE
Flixel is currently incompatible with OpenFL 4.0.0 or above. Please use version 3.6.1 or older.

### ISSUE THREAD

**Issue by pywebdesign** [HaxeFlixel/flixel#1902]
- **Flixel version:** 4.1.1
- **OpenFL version:** above 4.0.0
- **Lime version:** 3.0.3 (command-Line tools)

_______________________________

**Code snippet reproducing the issue**:

Simply download an install like explained in the getting started tutorial
add line to the hello world example for menu

http://haxeflixel.com/documentation/hello-world-command-line/

run
```
    >lime test neko
```
**Observed behavior:**

/usr/lib/haxe/lib/flixel/4,1,1/flixel/system/macros/FlxDefines.hx:81: characters 41-60 : Flixel is currently incompatible with OpenFL 4.0.0 or above. Please use version 3.6.1 or older.

**Expected behavior:**
The tutorial should work on a fresh install

**what happen when you downgrade openfl to 3.6.1**

/usr/lib/haxe/lib/flixel/4,1,1/flixel/system/macros/FlxDefines.hx:86: characters 41-60 : Flixel is currently incompatible with Lime 3.0.0 or above. Please use version 2.9.1 or older.

**Comment by larsiusprime** [comment]
The reason for this is that OpenFL 4.0 removes the drawtiles api, which flixel currently relies on. Until we have time to rewrite the flixel renderer to use the new tilemap api (something we might put our fundraiser money towards), this incompatibility will remain in place. The best we can do in the meantime is to give these error messages directing what versions of openfl/lime you need to use.

**Comment by pywebdesign** [comment]
Thank you for the reply, i got it working by downgrading them!

I am quite new to flixel, so I am not here to judge at all.

Maybe add this information to the tutorial as it is probably the first contact for many other new user with flixel. It could discourage quite a lot!

**Comment by larsiusprime** [comment]
Definitely needs a disclaimer in docs!

**Comment by Gama11** [comment]
I guess the problem is that the tutorial instructs to download Lime first, which then gets the latest version. If Flixel was installed first, it would probably install the correct Lime version that is listed as a dependency in `haxelib.json`.

**Comment by Tembac** [comment]
At least a sticky on the forum with a warning can be useful. I just updated the libraries and didn't remember this.

**Comment by mastef** [comment]
It would be awesome to have this, as the latest openfl/lime now switched from Ant build process to Gradle. So many sweet things coming

Is there anywhere we can track or contribute to the progress? Any estimate on the workload?

**Comment by Tembac** [comment]
I think @Beeblerox is working on this. You can check out his public activity. It seems like a big change so I suppose it will take a while to develop and test.

https://github.com/Beeblerox?tab=activity

**Comment by Gama11** [comment]
I can't reproduce the issue @pywebdesign originally had here - if you run `haxelib install flixel` like instructed [here](http://haxeflixel.com/documentation/install-haxeflixel/) in the getting started guide, it automatically installs the correct versions of Lime and OpenFL as well.

[Now, in the setup section of the tutorial](http://haxeflixel.com/documentation/setup/), this will not be the case, since Lime is installed first.

**Comment by KosnIre** [comment]
I ran into this issue because the [Getting Started instructions](http://haxeflixel.com/documentation/getting-started/) link to the OpenFL download page:

> 1. Install OpenFL and Haxe

Following their instructions installs the latest versions of Lime and OpenFL.

Then HaxeFlixel Getting Started step 2 (_Install HaxeFlixel_) installs the correct flixel dependency versions.

I was able to correct the issue and get "Hello World" running (in neko at least) by using `haxelib set openfl 3.6.1` and `haxelib set lime 2.9.1` ([found here](http://old.haxe.org/doc/haxelib/using_haxelib)). You can confirm the version settings with `haxelib list`.

**Comment by Gama11** [comment]
Right, that's a good point.. Can probably just remove that step.

**Comment by KosnIre** [comment]
> Can probably just remove that step.

Yes, but there should at least be a link to install Haxe by itself (otherwise haxelib cannot be run).

Oddly, [OpenFL's download page](http://www.openfl.org/learn/docs/getting-started/) gives me Haxe 3.2.1-win where [Haxe's download page](http://haxe.org/download) gives me 3.3.0-rc.1-win. I'm not sure if there's a significant difference. I'm new here.

**Comment by Gama11** [comment]
Yeah... both should be ok really. 3.3.0-rc1 is _technically_ a "release candidate" though, so not a "stable release".

**Comment by MSGhero** [comment]
3.3.0 is 3 months overdue :)

**Comment by KosnIre** [comment]
Going through [the Tutorial](http://haxeflixel.com/documentation/setup/) now and I see that http://haxe.org/download is used there (in Step 1). So, it makes sense to use that in the Getting Started page for consistency. I also see that [Gama's change above](https://github.com/HaxeFlixel/flixel-docs/commit/4ba737d5e53f0d121679a49ccaee90a8638865d7) will address the installation instructions there.

**Comment by paulorobertocruz** [comment]
Just to point out here.
To this date when you install haxeflixel whiout openfl and lime on your haxelib, the correct openfl and lime versions are instaled. But when running haxelib run openfl setup, openfl downloads another version of lime and some may be cofused to why a problem may be acurring when they try to run flixel. This order of instalation and config gets two lime version on the haxelib, assuming openfl and lime are not installed. But not problem if this is clear to newcomers.
haxelib install flixel
haxelib run openfl setup
haxelib lime setup
haxelib set lime 2.9.1

So if the last step is not done the warning will still occur and the project will not run.

**Comment by Gama11** [comment]
Moved this issue to flixel-docs: https://github.com/HaxeFlixel/flixel-docs/issues/184

**Comment by mastef** [comment]
Is the lime limitation also/still necessary? Have a few blockers like https://github.com/openfl/lime/issues/815 due to this

**Comment by Gama11** [comment]
It is, see #1940.

**Comment by nykevinwong** [comment]
@larsiusprime 
any idea of when rewriting flixel renderer can be done?
can you post the more detail description of the changes/files need to be rewritten in order to make Haxeflixel to work with openfl 4.0+ ?

larsiusprime :
The reason for this is that OpenFL 4.0 removes the drawtiles api, which flixel currently relies on. Until we have time to rewrite the flixel renderer to use the new tilemap api (something we might put our fundraiser money towards), this incompatibility will remain in place. The best we can do in the meantime is to give these error messages directing what versions of openfl/lime you need to use.

**Comment by ibilon** [comment]
@nykevinwong There's https://github.com/HaxeFlixel/flixel/pull/2136 which allows using flixel with openfl 8.

**Comment by larsiusprime** [comment]
@nykevinwong Was about to say the same as @ibilon. This issue is something we've known about for a long time and have been working to solve.

**Comment by nykevinwong** [comment]
in case anyone need to know how rendering system of haxeflixel works. below article might be userful. https://haxeflixel.com/blog/01-HaxeFlixel-rendering/
