### ISSUE TITLE
Playing animation with larger than current frame still displays smaller frame size on flash, html5

### ISSUE THREAD

**Issue by IBwWG** [HaxeFlixel/flixel#1937]
Exactly the same code and versions as in #1936 but you can see in the image that the red block is 10x10 instead of 20x20 as prescribed by its atlas definition:

![hf-debugdraw](https://cloud.githubusercontent.com/assets/16719964/18346018/7927562e-75be-11e6-9ff5-d1f4a4d920e3.png)

Only affects flash though.  The output should look like on cpp:

![hf-animsizebug](https://cloud.githubusercontent.com/assets/16719964/18346134/14341328-75bf-11e6-9b3d-06f4a590404d.png)

(With the exception of the debugdraw output still being wrong on cpp, but that's #1936's bug.)

**Comment by Gama11** [comment]
Are you sure it's the same code as in #1936 you used for those screenshots? The red box doesn't appear in the upper-left corner of the white one for me, more in the middle.

**Comment by IBwWG** [comment]
I had just copied and pasted from there...notice that I changed the offset before updating the picture.

**Comment by IBwWG** [comment]
Confirmed again, try updating your code from 1936 as it is now.

**Comment by Gama11** [comment]
HTML5 seems to be consistent with Flash here, so this may be about `FlxG.renderBlit` vs `FlxG.renderTile`.

**Comment by Beeblerox** [comment]
i think that this "issue" is caused by incorrect atlas data:
1) atlas image size is 100x100 pixels
2) you try to add frame with the name "b/0" which image starts at (90; 90) and have size of (20; 20), which means that bottom right corner of frame image is at (110; 110) on atlas image, but this point is out of bounds of atlas image. 
3) frame generates from this data and frame have UV property, which is used in tile render mode (usually on cpp target), and UV values for bottom right corner of frame is (1.1; 1.1) - larger than 1.0
3) And here is why you have different visual output on flash and cpp targets - on flash it doesn't use UV data and just copies part atlas data to camera buffer, on cpp target it uses UV data and i think that texture repeating is on, so you're drawing quad with repeating texture which result in bigger visual output.

On your side: you should provide correct data
On flixel side: we could add more checks to atlas parsing methods to prevent or minimize such cases
