### ISSUE TITLE
A (0,0) FlxVector normalizes to (1,0)

### ISSUE THREAD

**Issue by guifes** [HaxeFlixel/flixel#1958]
I was normalizing a zero vector when I got a (1,0) one. I've inspected the FlxVector class and found out this:

```haxe
public function normalize():FlxVector
{
	if (isZero()) 
	{
		x = 1;
		return this;
	}
	return scale(1 / length);
}
```
Shouldn't it look more like this?

```haxe
public function normalize():FlxVector
{
	if (isZero()) 
	{
		return FlxVector(0, 0);
	}
	return scale(1 / length);
}
```

**Comment by Gama11** [comment]
Hm.. @Beeblerox?

**Comment by guifes** [comment]
Also, why is FlxSprite velocity property a FlxPoint instead of a FlxVector?

**Comment by Beeblerox** [comment]
i think you're right. it should return zero vector in this case. feel free to send PR if you want to
About sprite's velocity being vector instead of point: there is a discussion about getting rid of FlxPoint class (here https://github.com/HaxeFlixel/flixel/pull/1762 and here https://github.com/HaxeFlixel/flixel/issues/1856). I'm agree about it. but had no time to make it myself
