### ISSUE TITLE
FlxAtlas crash

### ISSUE THREAD

**Issue by starry-abyss** [HaxeFlixel/flixel#2025]
- **Flixel version:** after and including 06ac60e
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:** neko

________________________________

Just run the project as it is: https://github.com/starry-abyss/render_test_cpp

My output is:
```
Invalid field access : h
Called from flixel.graphics.atlas.FlxAtlas::hasNodeWithName line 684
Called from flixel.graphics.atlas.FlxAtlas::addNode line 182
Called from PlayState::create line 26
Called from flixel.FlxGame::switchState line 649
Called from flixel.FlxGame::create line 350
Called from openfl._legacy.events.EventDispatcher::dispatchEvent line 98
Called from openfl._legacy.display.DisplayObject::__dispatchEvent line 182
Called from openfl._legacy.display.DisplayObject::dispatchEvent line 70
Called from openfl._legacy.display.DisplayObject::__onAdded line 362
Called from openfl._legacy.display.DisplayObjectContainer::__onAdded line 379
Called from openfl._legacy.display.DisplayObject::__setParent line 423
Called from openfl._legacy.display.DisplayObjectContainer::addChild line 31
Called from Main::new line 11
Called from DocumentClass::new line 217
Called from DocumentClass::$init line 217
Called from Type::createInstance line 108
Called from ApplicationMain::main line 119
Called from openfl._legacy.Lib::create line 122
```

**Comment by Gama11** [comment]
The problem is that you're initializing `atlas` right where it's declared (rather than in `create()`). This code will be executed in the `PlayState`'s constructor, which happens _before_ the actual state switch. Since the graphics cache is cleared between state switches (including `FlxAtlas`, since 06ac60e it registers a listener to `FlxG.signals.preStateCreate`). By the time you want to use the atlas, it has already been destroyed.

So you have this order of events:

- `PlayState#new()` creates a `new FlxAtlas()`
- `FlxAtlas#destroy()` is executed
- `PlayState#create()` is executed

This used to be (or still is?) a common issue with `FlxText` objects as well.

@Beeblerox Not sure if this is worth fixing / fixable?

**Comment by Gama11** [comment]
I don't think we should do anything here, see my previous explanation. You should create your objects in `create()` rather than `new()`.
