### ISSUE TITLE
background color control is confusing

### ISSUE THREAD

**Issue by raould** [HaxeFlixel/flixel#2029]
- **Flixel version:** 4.2.0
- **OpenFL version:** 3.6.1
- **Lime version:** 3.5.2
- **Haxe version:** 3.2.1
- **OS**: ubuntu 14.04 lts 64 bit intel
- **Affected targets:** neko

________________________________

change Project.xml's "<window>" to have background="#00FF00" e.g.
```
    <window width="320" height="480" fps="60" background="#00FF00" hardware="true" vsync="true" />
```

**Observed behavior:** the FlxState's background color is black.
**Expected behavior:** my PlayState which extends FlxState has a green background per Project.xml

**Comment by Gama11** [comment]
That's the Window's background - the default `FlxCamera` has its own background on top of that though, which defaults to black.
With `bgColor = FlxColor.TRANSPARENT;` in your state, you can make the window background visible. Or alternatively just change that one instead of the `<window>` background in the first place.
