### ISSUE TITLE
How to design classes?

### ISSUE THREAD

**Issue by ashes999** [HaxeFlixel/flixel#2086]
I posted a question [on the forums here](http://forum.haxeflixel.com/topic/564/haxeflixel-use-case-ecs) about architecture, ECS, and HaxeFlixel. I didn't get a good reply, so here's a refined version of my question:

When I'm using HaxeFlixel, while I can use any of the below options, which way is best or works best with the framework? This is for "domain object" classes like monster/player/etc.

- Domain object class subclasses Flixel classes (usually `FlxSprite` and friends)
- Domain object class keeps an instance of a Flixel class as a member variable
- Domain object class is an entity and Flixel classes make up components

I tried the third option but the data sharing and redundancy was weird; eg. I have a `Position` component and an `Image` component, but both use a (shared?) `FlxSprite` instance somehow, and I have to synch property values (usually component => flixel class).

It seems to me that HaxeFlixel wasn't designed to be used this way, so which of the other two options makes the most sense? How can I best design my classes/architecture when using HaxeFlixel?

**Comment by MSGhero** [comment]
If you need to override something, like the default `update()` behavior, you should subclass since flixel is internally handling children of the current `FlxState`. Otherwise, the first two are personal preference, the difference between using `myObject` versus `myObject.sprite`.

I think this would have been better suited for the forums anyway.

**Comment by Gama11** [comment]
Please don't use the issue tracker for questions - that's why we have the forums / Slack / etc.

**Comment by ashes999** [comment]
Sorry. I tried the forums but didn't get any reply. I'll try Slack next time.

**Comment by DleanJeans** [comment]
It seems like my answer doesn't appeal to you.
I'm also interested in an ECS engine built on HaxeFlixel just like you.
There's also a Discord server where you are welcomed to join and it's more crowded and noisier than the Slack server.

**Comment by ashes999** [comment]
@DleanJeans I'm not sure if I want an ECS or not. I'd rather ask: how is HaxeFlixel meant to be used? See [this thread on GameDev.SE](https://gamedev.stackexchange.com/questions/117602/updating-a-multithreaded-entity-component-system/117609); the top answer suggests that an ECS is not necessarily such a good idea (at least in the traditional design of ECS) as far as I understand it.

**Comment by JoeCreates** [comment]
Flixel is a bit of an inheritence mess. You are expected to just extend
whatever closest matches the behaviour you require, which is gine up until
the point that you also want to use your new extended behaviour from a
different base class.

You can mitigate this issue to some extent by not following flixel's
example and using a more composition focussed design, where behaviours are
members rather than subclasses. Unfortunately adding these members still
requires subclassing if only to add that member.

For example, if you want a FlxSprite that has the behaviour of a chest or
container that can be opened and closed, you could extend FlxSprite and add
an open bool and perhaps signals for when it opens and closes. If you then
wanted to add this same behaviour to a FlxTilemap (which doesn't extend
FlxSprite) or a FlxText (which already extend FlxSprite and cant extend
your new behavior) you would end up having to reimplemeny the behavious
multiple times. Flixel is fundamentally flawed like this. The issue is
especially prevalent in flixel addons where new behaviour is almost
exclusively added by extending flixel classes, making these behaviours
mutually exclusive. *sigh* There is an open issue about this. The problem
is that it is a very fundamental and huge redesign required to make it into
a more composition based design.

However, you can still use a compositional approach on top of flixel. For
example, instead of extending FlxSprite to have all the behaviour of
something which can be ope ed and closed, you could write an Openable
component which has this behaviour, then extend FlxSprite such that it has
obly a single new member pointing to this component. This way you could add
this behaviour to a FlxTilemap or FlxText much more easily without
reimplementing the entire thing. Furthermore, you can use interfaces to
identify classes that contain particular conponents. For example a
FlxSprite could implement Openable which means it has an OpenableComponent
member.

Sometimes you may have a component that needs to be initialised or updated,
which is still possible, but when extending your FlxSprite or whatever you
would need to remember to do these extra things like calling init in new or
myComponent.update in the FlxSprite's update method. This is vastly
preferable to naive inherientence but can result in a lot of boilerplate.

This led me to write a system which does all that stuff automatically with
the magic of haxe macros. If you check out the components package of my
Lycan project on github you will find the macros and some examples of how
they are used. Essentially it lets you define components as an interface
and component class that extend Entity and Component respectively. Now you
can make any class implement the interface and the vuild macro will
automatically add the component member and instantiation. Furthermore you
can use special metadata on methods in the component class such as append
and prepend which specify that the methods should be called in specific
places in any Entity with that component. For example if you had a
component which needed to be updated whenever the parent FlxSprite is
updated, you would specify this in the component itself and never again
have to worry about it because the macro will automatically build that code
into your Entity. Essentially this system does the composition+interfaces
approach, but automates all of the boilerplate so that your classes stay
clean and concise and the chance of human error is reduced.
