### ISSUE TITLE
FlxTextFormat example renders text incorrectly on HTML5 target

### ISSUE THREAD

**Issue by baraujo** [HaxeFlixel/flixel#2132]
- **Haxe version:** 3.4.7
- **Flixel version:** 4.3.0
- **OpenFL version:** 3.6.1
- **Lime version:** 2.9.1
- **Affected targets:** HTML5
Tested with Windows 10 Home 1709 on:
Chrome 64.0.3282.186 64 bits
Firefox Quantum 58.0.2 (64-bit)

________________________________

**Code snippet reproducing the issue**:
Just create a FlxTextFormat example:
```
flixel c [choose 48]
cd FlxTextFormat
lime test html5
```
________________________________

**Observed behavior:**
![html5](https://user-images.githubusercontent.com/587621/36825361-48353a3c-1cdd-11e8-8b73-9f87eed213a8.PNG)
**Expected behavior:** (lime test neko)
![neko](https://user-images.githubusercontent.com/587621/36825240-c6f67f9e-1cdc-11e8-9bb5-41bcfbf61431.PNG)

**Comment by Gama11** [comment]
This is to be expected, text format ranges (which `FlxText` uses for this) were not implemented in OpenFL 3.6.1's `TextField`.

I tested how this looks like with OpenFL 8 via #2136, and it seems text format ranges are implemented now, but still a bit buggy: https://github.com/openfl/openfl/issues/1861.

Closing since this is something that will have to be fixed on the OpenFL side.
