### ISSUE TITLE
Block Flixel mouse events when a debugger interaction tool is active

### ISSUE THREAD

**Issue by Gama11** [HaxeFlixel/flixel#2155]
If there's a `FlxDebugger` interaction tool active, all flixel mouse events should be blocked using `FlxG.mouse.enabled`, similar to what `FlxDebugger` itself already does when it gains / loses focus. Otherwise, you end up triggering button callbacks or similar instead of selecting or moving elements.

This seems to require changes to how `FlxG.mouse.enabled` works (if it's disabled, all currently held buttons need to be marked as released), and maybe `FlxDebugger`'s handling of it too.

**Comment by Dovyski** [comment]
I can work on this. If I am not mistaken, `FlxDebugger` already does some internal working to properly handle mouse clicks on debug buttons/overlays (ignoring game mouse events). In theory, we mainly need to worry about flixel mouse events.

**Comment by Geokureli** [comment]
Just wanted to chime in and say that, currently, clicking a debug window doesn't block mouse events to the FlxGame/FlxMouse. If I click a debug window, not only does the mouse event trigger in Flixel, but it was processed in FlxMouse before the debug window. this is because FlxMouse is adding MouseEvent listeners to the stage
