### ISSUE TITLE
HTML target weirdness on macOS

### ISSUE THREAD

**Issue by starry-abyss** [HaxeFlixel/flixel#2235]
- **Haxe version:** 3.4.7
- **Flixel version:** 4.6.3
- **OpenFL version:** 8.9.5
- **Lime version:** 7.6.3
- **Affected targets:** html5

________________________________

**Code snippet reproducing the issue**:

The game:
https://igorsgames.itch.io/from-the-deep

Source code:
https://github.com/starry-abyss/ld34

compiled from Windows

________________________________

**Observed behavior:**
on macOS: in Safari the game hangs after introduction screen, in Firefox there is no level (!?), and character just falls infinitely from top into the sea.

**Expected behavior:**
in Firefox and Chrome on Windows the game runs fine.

**Comment by starry-abyss** [comment]
Here are some console messages:

firefox:

> Use of the motion sensor is deprecated. ld34.js:275:9
> Error: WebGL warning: texImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads. ld34.js:60926:9


safari:

> [lime.utils.AssetLibrary] WARNING: Could not load "assets/music/track1.ogg"
> ld34.js:11863

....

> [Log]  (1) (ld34.js, line 105253)
> get_length — ld34.js:115167
> init — ld34.js:33073
> load — ld34.js:37597
> startMusic — ld34.js:6711
> create — ld34.js:6747
> switchState — ld34.js:13030
> update — ld34.js:13067
> step — ld34.js:13058
> onEnterFrame — ld34.js:12992
> __dispatchEvent — ld34.js:1174
> __dispatch — ld34.js:2014
> __broadcastEvent — ld34.js:105075
> __onLimeRender — ld34.js:106064
> dispatch — ld34.js:58834
> handleApplicationEvent — ld34.js:351
> [Error] TypeError: null is not an object (evaluating 'this.__buffer.get_src().duration')
>     __handleError (ld34.js:105262)
>     __broadcastEvent (ld34.js:105079)
>     __onLimeRender (ld34.js:106064)
>     dispatch (ld34.js:58834)
>     handleApplicationEvent (ld34.js:351)

**Comment by Geokureli** [comment]
You should try debugging them with your IDE on these browsers in order to get more haxe-related error stacks. typically I'll just load `http://127.0.0.1:3000` or whatever port you're using in these browsers after building with -debug. every browser has some different quirks, especially Safari. If you find some that you think Flixel could account for, let us know

**Comment by starry-abyss** [comment]
Thank you, I'll try debugging it myself too, when I have more time. Maybe there is something quirky in the way I'm playing/loading sounds.

**Comment by Geokureli** [comment]
I forgot to mention this before, but after looking around for a little, I noticed that not all browsers play ogg, and since mp3 is public domain, now, I believe it has become more supported. I recall issues with mp3 on chrome prior, but that is no longer the case. My game's Mp3s work on all 3 of these browsers.

Any error thrown from non-essential things like audio can still exit the stack on following lines of essential code.

**Comment by starry-abyss** [comment]
OK, so I worked around the issues:
- the Safari one by using mp3 instead of ogg vorbis, as Geokureli suggested;
- the one with Firefox by using .csv for levels directly instead of FlxStringUtil.bitmapToCSV.

Would be nice to get some warnings from the engine instead of crashes, but yay, the game works :D
Also still sometimes the pickup sound starts playing a bit and then stops, going to investigate it later.
