### ISSUE TITLE
Linux wont compile

### ISSUE THREAD

**Issue by Noob1fy** [HaxeFlixel/flixel#2627]
(might be bc im on chromebook)

- **Haxe version:** 4.1.5
- **Flixel version:** 4.11.0
- **OpenFL version:** 9.1.0-LqBuHo
- **Lime version:** 7.9.0
- **Affected targets:** HTML5

________________________________

**Code snippet reproducing the issue**:
![image](https://user-images.githubusercontent.com/111801657/186046650-05bb2428-0975-4ebc-a140-d13dd1434ea1.png)

**Comment by Geokureli** [comment]
try `haxelib lime rebuilt tools` and `haxelib run lime setup`, you might be using an older lime command than the one you installed mot recently

otherwise I'm not sure, I've successfully ran this same combination (I think). You might have better luck asking in the [OpenFL forum](https://community.openfl.org/) as this might be a lime issue

**Comment by NoobifyDev** [comment]
![image](https://user-images.githubusercontent.com/111801657/186240594-8a1aa270-6b4a-4b42-85e5-5782662696f9.png)

**Comment by Geokureli** [comment]
> `haxelib lime rebuild tools` ![image](https://user-images.githubusercontent.com/111801657/186240831-ca3b82ef-cd1b-44ef-9f28-7a40f292a105.png)

Try the other command I gave

**Comment by Noob1fy** [comment]
its fine i have a working windows pc i dont need it on a chromebook and i think more something with specs than haxeflixel so ima just close

**Comment by Geokureli** [comment]
I'm confused, did you try the command and something didn't work or you just don't wanna?

**Comment by Noob1fy** [comment]
i tried it, i even installed format and stuff and it wont work.
