### ISSUE TITLE
seriously, fix the FlxText Memory Leak when updating text

### ISSUE THREAD

**Issue by TheRealJake12** [HaxeFlixel/flixel#2707]
- **Haxe version:** 4.2.5
- **Flixel version:** 5.1.0
- **OpenFL version:** Latest
- **Lime version:** Latest
- **Affected targets:**
All I'm pretty sure but windows for sure
________________________________

**Code snippet reproducing the issue**:
make a flxtext and have it update a ton between different texts.

________________________________

**Observed behavior:**
Memory Goes Really High.
![image](https://user-images.githubusercontent.com/84357907/209508239-9b524dae-cf7e-4bed-b31d-e61fc1afa4ee.png)

https://user-images.githubusercontent.com/84357907/209508488-af792790-5ff5-4156-ad76-2966a557790d.mp4

**Expected behavior:**
Memory Doesn't Go Extremely High

**Comment by MemeHoovy** [comment]
thought this was fixed by NeeEoo via: https://github.com/HaxeFlixel/flixel/pull/2656

**Comment by TheRealJake12** [comment]
nope.

**Comment by Geokureli** [comment]
create a small test project that reproduces this issue and I'll look into it, I've made tests myself and had trouble seeing it this bad.
 
 Also I would use FlxBitmapText in the case of your project. FlxText draws an openfl textfield to a bitmap, and creates new bitmaps whenever the size changes, where FlxBitmapText just renders each char from a spritesheet.

At the end of the day you're creating a 100 bitmaps every second and discarding them over and over, and it waits until a garbage collection cycle to free them up because thats how managed memory works, this way has a lot of benefits in a lot of cases and it may not be best to change it just because it doesn't work in this one case. part of being a software developer is working around these limitations.

Again, create a test I'll see if there's an elegant solution, but you can avoid this all by using FlxBitmapText, or just not spamming a dozen FlxTexts redraws every frame

**Comment by Geokureli** [comment]
Also, just wanna remind you real quick that I'm not paid to work on flixel. When I can, I donate spare time to improving this. and there's a lot of things to improve. I saw this issue at 1 AM on Christmas day and responded 3 hours after it was made. And then in the morning I see that you called me out on social media 8 hours before you even made this issue, to that I can only say "what the fuck is wrong with you?"

This might be one of the most entitled things I've ever witnessed in my life. The equivalent of "C'mon dude, when are you gonna fix this bug that I haven't even brought up yet, that only happens when I do careless things at ridiculous speeds without regard of any consequences. it's not like it's 1am on a holiday recognized by a majority of the world, or something."

So with that in mind, I hope you understand that I likely won't get to this, before my other tasks, and if you act like this on social media again, I'm gonna block you

**Comment by MemeHoovy** [comment]
uh, @Geokureli wtf did they do?

**Comment by TheRealJake12** [comment]
![image](https://user-images.githubusercontent.com/84357907/209585857-5d1112a2-58e0-4b7f-8f1d-11b0d695c3ca.png) explaination

**Comment by TheRealJake12** [comment]
didn't mean to sound rude my man. I understand its christmas but damn didn't have to go on a rant.

**Comment by Geokureli** [comment]
The other issue was resolved, after a change was made, so saying it was ignored is just wrong. Didn't mean to go all out, I just literally thought you were telling everyone I'm ignoring you before you even posted the issue

**Comment by Geokureli** [comment]
reopening this, it's not resolved, and if others have the same problem they should see the workarounds listed above.

**Comment by TheRealJake12** [comment]
> The other issue was resolved, after a change was made, so saying it was ignored is just wrong. Didn't mean to go all out, I just literally thought you were telling everyone I'm ignoring you before you even posted the issue. I apologize for the reaction, there was a misunderstanding

my b. Its my fault. alrighty

**Comment by NeeEoo** [comment]
A way i usually fix this is setting a fieldWidth, since if you are on flixel 5 then the bug is fixed

**Comment by TheRealJake12** [comment]
:skull: thanks but I forgot about this
