### ISSUE TITLE
Making `FlxAnimationController.timeScale` static / adding a static variable for global animation speed.

### ISSUE THREAD

**Issue by CaptainBaldi** [HaxeFlixel/flixel#2936]
I've noticed that `timeScale` is a newer addition to the FlxAnimationController class. It is rather useful, however, I would personally see more use to it if it were static.

I've noticed that when created, #2913 initially had initially defined this field as static, but was changed due to not being useful in enough scenario's.

While I agree it is certainly not something that would be extremely common to use, I personally in a flixel project of mine have made an alias for `FlxAnimationController` that makes this field static, I did this to make a mode in the project that involves slowing down and speeding it back up, including animations.

Another example is Psych Engine, which also has this sort of implementation.

If making this field static isn't viable still, what about making a new static variable, something like `globalTimeScale`, and assign it a default value of say -1?

If you were to change this value to say something like 0.5, it would then affect all `FlxAnimationController`'s.

**Comment by Geokureli** [comment]
this is worth revisiting, I think now that there is an instance field for this, it's now easier to have a global manager. I talk about implementing this in the issue you linked

> I'm hesitant to add a global animation timeScale like your original PR had, I'm not a fan of using statics in classes like FlxAnimationController since they are hidden and esoteric, I'm already having regrets for FlxSpite.defaultAntialiasing

another example of this is `FlxCamera.defaultCameras`, which I want to phase out. I will always prefer global vars be put in `FlxG` rather than a class.

it's also worth mentioning that FlxG.timeScale already exists, but it effects everything, not just animation, but physics, tweens and timers. not sure if that covers your needs as well, you can also make time move faster for specific things by changing the `elapsed` arg in update calls. For instance, say your state has a few FlxGroups, one for characters, one for background elements and one for HUD/UI (or the DDR part of FNF), you can speed these up separately via:

```hx
override function update(elapsed:Float)
{
    //super.update(elapsed);
    
    characters.update(elapsed * 2.0);
    bgElements.update(elapsed * 2.0);
    ui.update(elapsed);
}
```

If we were to add something like FlxG.animationTimeScale, then I would likely have it multiply against every animations timeScale rather than replacing the ones using the default value. this makes more sense to me but, again, I kinda fail to see the need for a global scaler, the only use-case I can imagine is a FNF game that enables some hyper-mode effect that speeds everything up without speeding up the notes, and I would implement that differently

**Comment by CaptainBaldi** [comment]
Yes, I have tried implementing `FlxG.timeScale` into my project, however it slowing down practically everything does not suit my needs in certain scenarios, which is why I for example have an alias for `FlxAnimationController` in said project that incorporates global speeds.

Updating objects manually is viable, however it could be a small inconvenience, depending on how objects are set up in your game.

All in all it's just a small convenience feature.

On another note moving those types of statics to `FlxG` does sound like a good idea, I can agree they are quite esoteric.

**Comment by Geokureli** [comment]
If there was a PR to add `FlxG.animationTimeScale` i would approve it

**Comment by CaptainBaldi** [comment]
#2937 Done
