### ISSUE TITLE
FlxBitmapFont.fromAngelCode crashes on Flixel 5.6.0

### ISSUE THREAD

**Issue by Txori** [HaxeFlixel/flixel#3024]
- **Haxe version:** 4.3.3
- **Flixel version:** 5.6.0
- **OpenFL version:** 9.3.2
- **Lime version:** 8.1.1
- **Affected targets:** windows cpp, neko

________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxState;
import flixel.graphics.frames.FlxBitmapFont;
import flixel.text.FlxText.FlxTextAlign;
import flixel.text.FlxBitmapText;
import openfl.Assets;

class PlayState extends FlxState
{
	override public function create():Void
	{
        	var textBytes:String = Assets.getText("Assets/bmpFont.xml");
	        var XMLData:Xml = Xml.parse(textBytes);
	        var bmpFont:FlxBitmapText = new FlxBitmapText();
	        bmpFont.font = FlxBitmapFont.fromAngelCode(Assets.getBitmapData("Assets/bmpFont.png"), XMLData);
	        bmpFont.text = "HELLO";
	        bmpFont.alignment = FlxTextAlign.CENTER;
	        add(bmpFont);
	}
}
```

________________________________

**Observed behavior:**
The game crashes when trying to render the bitmap font at line: bmpFont.font = FlxBitmapFont.fromAngelCode(Assets.getBitmapData("Assets/bmpFont.png"), XMLData);
The error comes as a popup message that says: "info missing attribute charset".

Attached is my bmpFonr that I'm trying to use. I made it years ago, so the issue might come from the xml.

[bmpFont.zip](https://github.com/HaxeFlixel/flixel/files/14157222/bmpFont.zip)

**Expected behavior:**
This bitmapfont is working perfectly with flixel 5.5.0

**Comment by Geokureli** [comment]
I thought we left the xml stuff alone but something must have been broken when we added support for binary and text bmfont files, thanks for reporting this

**Comment by Geokureli** [comment]
i notice the xml file has the following info:
```xml
<info face="BMPFont" size="30" bold="0" italic="0" chasrset="" unicode="0" stretchH="100" smooth="0" aa="1" padding="0,0,0,0" spacing="0,0"/>
<common lineHeight="36" base="29" scaleW="256" caleH="256" pages="1" packed="0"/>
```
Note that `chasrset` seems to be misspelled and should be `charset`, and `scaleH` is `caleH`, have you manually edited this xml? After renaming it by hand it seems to work fine

I think we could improve the error messaging here, or make it so that these optional attributes don't crash the game

**Comment by Txori** [comment]
So it was really coming from the xml... I remember making that font+xml during a train trip something like 8 years ago... So I might have edited it at some point ^^'
I never saw those typos because everything was working fine until Flixel 5.6.0
Thanks!

If you're able to catch the misspelled attribute, an error message would be nice :)

**Comment by Vortex2Oblivion** [comment]
> - **Haxe version:** 4.1.0

Wait how are you using haxe 4.1.0 with flixel 5.6.0?
I thought it wouldn't let you use anything below haxe 4.2.5 in the latest versions.

**Comment by Txori** [comment]
Sorry, it's haxe 4.3.3, but haxelib 4.1.0
Too many things having almost the same name...

**Comment by Geokureli** [comment]
> If you're able to catch the misspelled attribute, an error message would be nice :)

Yes, adding better logging to the xml handlers, now

**Comment by Geokureli** [comment]
@Txori I'm thinking about ways to better broadcast these errors, and downgrading some of these issues since not all of the xml properties are even used, but I would like to point out that the errors I got from your xml did correctly explain the issue:
<img width="405" alt="Screenshot 2024-02-05 at 10 16 42 AM" src="https://github.com/HaxeFlixel/flixel/assets/2609513/e4efafa3-345e-4db8-a233-d7b78236acca">
