### ISSUE TITLE
PLUS key not being detected on QWERTZ layout

### ISSUE THREAD

**Issue by ACrazyTown** [HaxeFlixel/flixel#3090]
- **Haxe version:** 4.3.4
- **Flixel version:** 5.7.0@5ede2bd
- **OpenFL version:** 9.3.2
- **Lime version:** 8.1.1
- **Affected targets:** Windows 11

________________________________

**Code snippet reproducing the issue**:

```haxe
package;

import flixel.FlxState;

class PlayState extends FlxState
{
	override public function update(elapsed:Float):Void
	{
		if (FlxG.keys.pressed.PLUS) {
			trace("PLUS is pressed!");
		}
	}
}
```

________________________________

**Observed behavior:**
Pressing the PLUS key would cause the trace to be printed.

**Expected behavior:**
Nothing happens.

I have a physical US QWERTY layout keyboard but I use the QWERTZ layout (called "Standard" on Windows). When I press the plus key on my keyboard anywhere else it properly types out a "+", however when I tried checking if plus was pressed in HaxeFlixel, I could never get it to work. 

Thru OpenFL's keydown event I found that the key was being recognized as "43". I've tried checking the key thru some online keycode testers and all of them report it as "187" aka plus. It's only Flixel (or maybe OpenFL/Lime) that recognizes it as "43".

The worst part is that my keyboard is a TKL, meaning it has no numpad, so I'm unable to increase the volume on any HaxeFlixel project.

**Comment by Geokureli** [comment]
I assume this is what you're using?
![image](https://github.com/HaxeFlixel/flixel/assets/2609513/deb1722a-aa42-4b81-a476-13b7885d511c)

Even though the keys are named things like PLUS, it typically refers to the + key in the stanard English keyboard layout. Note that in software development keyboard events' keyCodes are not the same as charCodes, in fact the distinction only becomes more clear when dealing with non-standard-english keyboards.

I haven't tried but I assume your Z key is still on key 90, but key 90 was moved in your keyboard, whereas + was moved to a different button. I think this is made even more confusing by the fact that there really is no PLUS key, if anything, there's an EQUAL key, but we just call it PLUS for some reason. if you wanted to get the plus on the keyboard pictured, i would use THREE

To fix, you can use openfl keyboard events to get the charCode, I believe this would still require you hold shift when you press 3, or you can simply press the Ü key on your keyboard, which might work, since it's in the same location as my + Here's a [handy keycode guide](https://www.toptal.com/developers/keycode)

**Comment by ACrazyTown** [comment]
I use the Croatian version of QWERTZ:
![image](https://github.com/HaxeFlixel/flixel/assets/47027981/5423a8f6-37ff-4e0d-8bc4-29298eee2264)

Pressing the plus(?) key right next to backspace returns 187 on the website you linked and also a few others I've tried. Only Flixel seems to recognize it as key 43 for whatever reason

**Comment by Geokureli** [comment]
sorry for the misunderstanding, I'll look into this, I would also raise this issue with lime/openfl

**Comment by Geokureli** [comment]
> OpenFL's Keyboard class has some commented out code for the plus key which I'm thinking may be the cause. Should I make an issue on OpenFL's repository?

Yes, please, link this issue in it and link the code you're referring

**Comment by ACrazyTown** [comment]
After digging around a bit more I'm confused as to what the issue is. 
Both SDL and Lime detect the PLUS key as 43, OpenFL's Keyboard has only [one mention of PLUS](https://github.com/openfl/openfl/blob/develop/src/openfl/ui/Keyboard.hx#L589) but it's commented out and it's also 43. 

It only seems to happen on native targets (I've only tried Hashlink so far), on HTML5 the keycode is 187.

I've found this [line in FlxKeyboard](https://github.com/HaxeFlixel/flixel/blob/master/flixel/input/keyboard/FlxKeyboard.hx#L54) that seems related but it's Mac only for whatever reason. Removing the Mac conditional fixes the issue. Is there a reason why it's Mac only or?

**Comment by Geokureli** [comment]
> I've found this [line in FlxKeyboard](https://github.com/HaxeFlixel/flixel/blob/master/flixel/input/keyboard/FlxKeyboard.hx#L54) that seems related but it's Mac only for whatever reason. Removing the Mac conditional fixes the issue. Is there a reason why it's Mac only or?

@NeeEoo, care to comment, re: https://github.com/HaxeFlixel/flixel/pull/2987

**Comment by NeeEoo** [comment]
I didnt know it happened on non mac platforms too, feel free to remove the conditional
