### ISSUE TITLE
FlxAnimationController.finishCallback does not trigger on looped animations

### ISSUE THREAD

**Issue by balajeerc** [HaxeFlixel/flixel#3212]
Not sure if I'm misunderstanding how `FlxAnimationController.finishCallback` works but looks like the callback is not getting triggered.

To reproduce this, one can add the following lines after [line 83 of FlxAsperiteUtil demo](https://github.com/HaxeFlixel/flixel-demos/blob/dd0afb866ed57b0507e8679d191ce68d4a8e2407/Graphics/FlxAsepriteUtil/source/PlayState.hx#L84):

```
player.animation.finishCallback = (animationName:String) -> {
    trace("animation complete callback: " + animationName);
 };
player.animation.callback = (name:String, frameNumber:Int, frameIndex:Int) -> {
    trace("per frame animation callback: " + name + " " + frameNumber + " " + frameIndex);
};
```

On running the demo post addition of lines above, I notice that the `finishCallback` is not called, whereas the per frame triggered `callback` is indeed called.

**Comment by Geokureli** [comment]
It appears that finishCallback is not called when the animation is set to loop, I suppose this is by design, since a looping animation is never "finished". That said, I agree that this is weird behavior, there is [a separate issue to create a finished signal](https://github.com/HaxeFlixel/flixel/issues/3204) to replace this callback, perhaps a change can be made there, alternatively we can have 2 signals, one when the end is reached and one when it stops playing

**Comment by Geokureli** [comment]
@balajeerc, looking into this now, note that finished callback is fired when the final frame is done, rather than when it is reached. If this were extended to include loops, it would be fired when the animation goes from the last frame back to the first frame, so this might be a little confusing seeing the finished callback whenever frame 0 is "reached". It is also confusing because `animation.finished` is still false.

I think an immediate fix for your case is to use:
```hx
animation.callback = function(name, num, index)
{
    if (num == animation.curAnim.numFrames)
         trace("final frame entered");
    
    // alternatively
    
    if (num == 0)
         trace("loop complete");
}
```

In the future, I think if there is an event that includes both "finished" and "loop complete"  animations, it should avoid the word "finished". LMK if you have naming ideas

**Comment by balajeerc** [comment]
Firstly, thanks for looking into this @Geokureli 
I should have indeed filed it in flixel repo itself rather than the demo repo. Thanks for moving it.

The workaround you suggested is pretty much what I ended up using yesterday.

> LMK if you have naming ideas

Maybe `loopCompleteCallback`? Or even `loopComplete`?

**Comment by Geokureli** [comment]
> Maybe `loopCompleteCallback`? Or even `loopComplete`?

and on which frame would this fire?

**Comment by balajeerc** [comment]
> and on which frame would this fire?

@Geokureli I guess the PR that @richTrash21 submitted above solves it by firing it on the last frame. 
And that looks about right to me.

**Comment by Geokureli** [comment]
@richTrash21 does it fire on the last frame, or when it loops to the first frame?

**Comment by richTrash21** [comment]
> @richTrash21 does it fire on the last frame, or when it loops to the first frame?

It fires when the animation have just reached the loopPoint since the animation's loop was just completed. That means that if the animation has 3 frames and it's loopPoint set to the first frame (default value), the callback will fire when animation has just looped back to the first frame (loopPoint).

This also works with reversed animations, but for them the callback will be fired when the animation has looped to the last frame since it's considered "the first" frame in this case.
