### ISSUE TITLE
Add FlxMath.fastTan()

### ISSUE THREAD

**Issue by Vortex2Oblivion** [HaxeFlixel/flixel#3215]
```FlxMath.fastSin()``` and ```FlxMath.fastCos()``` exist so why not ```FlxMath.fastTan()```?
Considering that tangent is just sine divided by cosine it could be easily implemented with ```fastSin(x) / fastCos(x)```

**Comment by Geokureli** [comment]
I don't really see the point of fastCos or fastSin, how often are you using 100s of sin per frame and more importantly how often are you EVER using tan?

Also I'm strongly against [solutions in search of a problem](https://github.com/HaxeFlixel/flixel/wiki/Contribution-Guide#creating-new-features) if you have a valid need for this in a project, let me know

**Comment by Vortex2Oblivion** [comment]
May I ask if you're against having them, then why do they exist in the first place?

**Comment by Geokureli** [comment]
I didn't add them, they were in the flash version

**Comment by Vortex2Oblivion** [comment]
>  if you have a valid need for this in a project, let me know
People who make modcharting frameworks in flixel use [tangent in some of the modifiers a lot](https://github.com/search?q=repo%3AEdwhakKB%2FFNF-Modcharting-Tools+Math.tan&type=code) and it could help here.

**Comment by UncertainProd** [comment]
I think at this point, Math.sin is a bit faster than fastSin, at least when I tested it here:
https://try.haxe.org/#7b0FAA6C

And I also tested on cpp on windows and Math.sin seems to be faster

**Comment by Geokureli** [comment]
Your modcharting example doesn't seem to use tan 100s of times per second to the point where a faster implementation would have any noticeable effect, it also REALLY seems like this is a "Solution in search of a problem". I can't stress enough that I am only interested in PRs that offer solutions to problems you are actually facing now. not "Well this exists so maybe I should make this similar thing, I have no use for it, but other people might need it". Furthermore "fast" function like this need to be speed tested for performance before being added.

This issue raised red flags from the get go, because if there was any practical use for fast tan I would have expected to see an issue phrased like this:
"Hey I noticed some slowdown in my game and used profiling to determine that it's these costly Math.tan functions, I don't need the precision it offers so I researched a faster version and it made a noticeable difference. at first I was just gonna add it to my game's utils since it's like 4 lines of code, but then I saw FlxMath has similar tools so I thought I'd add it there". The dev :
1. discovers a problem in their game using dev tools for performance
2. fixes the problem in their game
3. tests the solution
4. adds the solution to Flixel
