### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Joalor64GH** [HaxeFlixel/flixel#3249]
My code is fine, it's just that I keep getting this compilation error:
```
Class<flixel.FlxG> has no field save
```

**Comment by Vortex2Oblivion** [comment]
> No??

What flixel version are you using

**Comment by Joalor64GH** [comment]
> > No??
> 
> What flixel version are you using

5.9.0

**Comment by ACrazyTown** [comment]
Make sure `FLX_NO_SAVE` is NOT defined in Project.xml

**Comment by Joalor64GH** [comment]
> Make sure `FLX_NO_SAVE` is NOT defined in Project.xml

It's not, but it wasn't there to begin with.

**Comment by Geokureli** [comment]
> My code is fine

Everyone says this, we still need to rule out any issues with your code, especially since I've never heard of anyone else having this issue.

Does this happen when you start a new project? does it happen when you run one of the demos? if not, it's likely your code and you need to create a small, shareable project that reproduces the issue, otherwise there's nothing we can do to help since none of us are seeing this issue.

**Comment by Joalor64GH** [comment]
I don't know how, but I solved the issue.
