### ISSUE TITLE
flixel needs their own discord server

### ISSUE THREAD

**Issue by FowluhhDev** [HaxeFlixel/flixel#3325]
i feel like if we had more than just one channel in the haxe server maybe more people who use haxeflixel could talk, since everyone talking/asking for help about haxeflixel the haxe server only talk about funkin' modding and rarely ever ask about their own games because they dont want to ask for help and/or use ai, so maybe instead of people flooding that chat with game modding we could have a new server with a channel dedicated entirely to modding and more channels for actual game dev so people can feel free to ask about code help, get feedback on their game, and maybe some off topic channels too.

thank you developers for hearing me out on this, hopefully you put this into careful consideration.

**Comment by moxie-coder** [comment]
why not just join an FNF discord server then? there’s already one that has modding channels and such, there’s no need for an flixel discord server, there’s already an flixel channel in the main haxe server and that’s good enough

**Comment by Geokureli** [comment]
> why not just join an FNF discord server then?

I believe they want a new discord to escape FNF

If there's problems with using the Haxe discord for flixel, we should figure out how to fix those problems. Creating a new server doesn't prevent those problems from happening again.

We do what we can to keep people from flooding the discord with FNF and it's gotten much better since the creation of the FNF project thread, which contains most of it. 

> since everyone talking/asking for help about haxeflixel the haxe server only talk about funkin' modding and rarely ever ask about their own games because they dont want to ask for help and/or use ai

Can you give examples? I don't recall anyone using ai, and plenty of people are discussing their own games in the #gamedev, #projects and #showcase channels.

Can you point these examples out to me in the discord?

**Comment by moxie-coder** [comment]
> > why not just join an FNF discord server then?
> 
> I believe they want a new discord to escape FNF
> 

oh okay I get it now, but it definitely wouldn’t help the issue, it would kinda defeat the purpose of the flixel channel honestly
