### ISSUE TITLE
Remove FlxTween - replace with Actuate lib

### ISSUE THREAD

**Issue by gamedevsam** [HaxeFlixel/flixel#538]
Actuate lib is easy to use and good on performance. It also has [nice documentation](http://haxe.org/com/libs/actuate). We should update tweening demo to use Actuate lib, and probably add an entry on the HaxeFlixel wiki that describes how to use the lib.

**Comment by MintPaw** [comment]
I'd like this to be reconsidered. Yes Actuate is unaware of HaxeFlixel's timescale, but that's probably pretty easily fixed by creating a custom actuator.

I recently tried to make an FlxTween un-aware of timescale [in this thread](http://haxeflixel.com/forum/?place=msg%2Fhaxeflixel%2FFukUoiAaKLQ%2FWpYsLqbzCAAJ). And in doing so I've come to realize how much of a mess FlxTween is, I can't even seem to tween FlxG.timescale or any static values right now do to some reflection problem, and starting multiple tweens with delays doesn't seem to work in some hard to reproduce situations.

There's open feature request for grouping of tweens and bounties on mass killing of tweens. This is why we had TweenMax despite fl.transitions.Tween and Actuate is completely factored out of OpenFL, tweening is really tough and needs some real attentions to work properly. In my opinion FlxTween should just interface with Actuate in the background.
