### ISSUE TITLE
Convert Dame exporters to work wih haxe

### ISSUE THREAD

**Issue by Beeblerox** [HaxeFlixel/flixel#69]
http://dambots.com/dame-editor/

**Comment by Gama11** [comment]
Dame doesn't seem too popular these days, compared to say, Tiled, so I'm not sure this is worth it. I also don't think it's being maintained anymore?

Either way, since the changes have to happen in Dame, not this repo, the issue should probably be moved there if you still feel it's relevant: https://github.com/XanderXevious/DAME/issues
